Category.create!([
  {label: "mythical creatures"},
  {label: "holidays"},
    {label: "Chanukah"},
    {label: "Christmas"},
    {label: "Halloween"},
  {label: "wedding/engagement"},
  {label: "frozen in time"},
  {label: "school"},
    {label: "teacher/librarian"},
    {label: "boarding school"},
  {label: "college/university/higher ed"},
    {label: "professor"},
    {label: "classics"},
  {label: "mythology"},
  {label: "assassin(s)"},
  {label: "spies"},
  {label: "hospital"},
  {label: "superhero"},
  {label: "parties"},
  {label: "animals"},
  {label: "shops"},
    {label: "bookstore"},
    {label: "restaurant/coffee shop"},
    {label: "sex industry"},
    {label: "grocery store"},
    {label: "florist"},
    {label: "bar"},
    {label: "bakery"},
  {label: "fandom"},
    {label: "convention"},
  {label: "slice of life"},
  {label: "business/professions"},
    {label: "detective/cop/agent"},
  {label: "apocalypse"},
  {label: "crime"},
  {label: "weather"},
    {label: "snow"},
    {label: "rain"},
  {label: "paranormal"},
  {label: "music"},
  {label: "summer camp"},
  {label: "transit"},
  {label: "travel"},
  {label: "magic"},
  {label: "family"},
  {label: "winter"},
  {label: "spring"},
  {label: "summer"},
  {label: "fall/autumn"}
])