Category.create!([
  {label: "mythical creatures", description: "This category includes prompts that involve magic and/or mythical creatures of some sort."},
  {label: "holidays", description: "This category includes prompts for all kinds of holidays."},
    {label: "Chanukah", description: "This category includes Chanukah-related prompts."},
    {label: "Christmas", description: "This category includes Christmas-related prompts."},
    {label: "Halloween", description: "This category includes Halloween-related prompts."},
  {label: "wedding/engagement", description: "This category includes prompts that might happen before, during, or after a wedding."},
  {label: "a different time", description: "This category includes situations where characters are thrown into a different time or the setting will not be modern day."},
  {label: "school", description: "This category includes prompts that cover non-college or university education, teachers included."},
  {label: "college/university/higher ed", description: "This category includes prompts that cover university and higher education, professors included."},
    {label: "classics and mythology", description: "This category includes prompts related to classics (Ancient Greece and Rome) and mythology."},
  {label: "assassins/spies", description: "This category includes prompts related to assassins or spies, whether about the target(s) or the perpetrator(s)."},
  {label: "hospital", description: "This category includes prompts related to hospitals and doctors, whether about patients or medical professionals."},
  {label: "superhero", description: "This category includes prompts related to superheroes or supervillains.  Sometimes both."},
  {label: "parties", description: "This category includes prompts related to parties that do not fit in another category (like holidays)."},
  {label: "animals", description: "This category includes prompts that involve animals or people who care for them."},
  {label: "shops", description: "This category includes prompts that take place at or involve shops like bookstores, coffee shops, and bars."},
  {label: "fandom", description: "This category includes prompts that involve fandom scenarios, such as interactions that take place at conventions."},
  {label: "slice of life", description: "This category includes prompts that are random life occurences (such as literally running into a stranger with a hot coffee) that do not fit in another category."},
  {label: "corporate/professions", description: "This category includes prompts that involve businesses or professions, such as cops, lawyers, and politicians."},
  {label: "apocalypse", description: "This category includes prompts that take place during or after the apocalypse."},
  {label: "crime", description: "This category includes prompts that relate to crime, whether about the target(s) or the perpetrator(s)."},
  {label: "paranormal/unexplained", description: "This category includes prompts about ghosts and unexplained events."},
  {label: "music", description: "This category includes prompts that involve music in some way."},
  {label: "transit/travel", description: "This category includes prompts that involve transit or tavel, including public transit and vacations."},
  {label: "family", description: "This category includes prompts that involve family interactions and scenarios."},
  {label: "seasons", description: "This category includes prompts that involve winter, spring, summer, or fall/autumn."},
  {label: "neighbors/roommates", description: "This category includes prompts that involve roommate or neighbor scenarios."},
  {label: "technology", description: "This category includes prompts that relate to the use and/or misuse of technology."},
  {label: "locations", description: "This category includes prompts that are location-based."},
    {label: "space", description: "This category includes prompts that are space-related."},
    {label: "woods", description: "This category includes prompts that involve the woods or forests."},
  {label: "sports/exercise", description: "This category includes prompts that involve sports and exercise, whether organized or otherwise."}
  {label: "dating/romance/sex", description: "This category includs prompts that have to do with dating, romance, and/or sex"}
])