Prompt.create!([
  #mythical creatures (-2, id 1)
  {text: "mermaids"},
  {text: "we’ve been dating for three months and you’re only now telling me you’re a werewolf"},
  #Chanukah (-3, id 2, id 3)
  {text: "I accidentally set the kitchen on fire frying things and you are an attractive firefighter."},
  {text: "What do you mean you’ve never played strip dreidel LET ME INTRODUCE YOU TO THIS PERVERSION OF THE GAME"},
  {text: "I know you’re just trying to take a smoke break but we ran out of matches and it’s Chanukah can I steal you for five minutes"},
  {text: "We both forgot to buy candles until the last minute and now there’s only one box left in the store"},
  {text: "My friend dragged me to their grandma’s ridiculous sufganiyot party and I don’t know anyone here but holy crap that person’s cute"},
  {text: "We are out of potatoes we are OUT OF POTATOES the latkes aren’t done this is not a drill please help"},
  {text: "We’re the only two people at this office ‘holiday’ party who seem uncomfortable with the way it’s all transparently Christmas stuff so let’s talk over here in a corner about how much we hate everything"},
  {text: "This Chinese restaurant is so crowded on Christmas Eve do you mind if we share a table?"},
  {text: "You seriously want me to teach you how to knit, just to make ugly Chanukah sweaters and prove a point?"},
  {text: "I agree with you that Chanukah is a minor holiday that we’re only making a big deal out of because of cultural forces surrounding Christmas but since we’re already at this youth group party in the synagogue basement do you maybe want to dance? :D?"},
  {text: "you were walking in front of me when you tripped over your own foot and knocked over the christmas tree in the park. let me help you up and we’ll try to fix the damage"},  
  #Christmas (-4, id 2, id 4)
  {text: "we both wore ugly sweaters to this christmas party because the invitation didn’t say it’s formal"},
  {text: "our landlord really went all out with the mistletoe, huh?"},
  {text: "my sister told me to buy this crappy toy for my niece and you work here please help me find it. it’s black friday and i’m afraid"},
  {text: "you need to stop your drunken caroling outside of my window at 2 am"},
  {text: "you’re kind of a scrooge and it’s up to me to show you the true meaning of holiday spirit hallmark movie style"},
  {text: "you left your christmas tree lights on over night and set the apartment building on fire. hey i live on the floor below you"},
  {text: "you keep coming into the store i work at to buy wreaths, what are you doing with all of these wreaths?"},
  {text: "you were walking in front of me when you tripped over your own foot and knocked over the christmas tree in the park. let me help you up and we’ll try to fix the damage"},
  #Halloween (-5, id 2, id 5)
  {text: "your costume is the superhero to my villain"},
  {text: "there are strange noises and I don’t want to sleep alone"}, #maybe put this in paranormal instead?
  {text: "I’m sorry I scared you so much in that haunted house I work at; here have my water"},
  {text: "I’m sorry my younger sibling egged your house… and that I helped"},
  #wedding/engagement (-6, id 6)
  {text: "i jokingly told you that the only way i’d marry you was if you did this weird outlandish thing, and you actually did it, and i’m kind of charmed"},
  {text: "this is probably a bad time, but marry me?"},
  {text: "we’ve been dating forever, and you just caught the bouquet at our friend’s wedding"},
  {text: "remember when we were in high school and we swore that if we were still single at 30 we’d marry each other, well hey guess whose birthday it is"},
  {text: "i planned out this super romantic proposal and you just ruined it by beating me to whole proposing thing"},
  {text: "we’re getting fake engaged for [insert reason here]"},
  {text: "we’re assigned to this mission in which we have to pretend to be a married couple, but i’m actually really in love with you"},
  {text: "we accidentally got married in vegas oops"},
  {text: "accidentally crashed this wedding, but hey you’re pretty cute"},
  {text: "i was deliberately not invited to this wedding so im crashing it anyways, even if that means the angry hot maid of honor is going to murder me"},
  {text: "you’re the hot stripper at my friend’s bachelor(ette) party"},
  {text: "hey i’m the best man, you’re a bridesmaid, let’s do this thing?"},
  {text: "i know im supposed to be your best man/maid of honor, but maybe i should mention now that i’m in love with you"}, 
  {text: "i’m a wedding planner and you don’t believe in marriage"},
  {text: "i’m your wedding planner, but i’m also falling in love with you"},
  {text: "i’m the wedding planner, and you’re the best man/bridesmaid"},
  {text: "my ex just invited me to their wedding and i need you to be my date so it doesnt look like ive spent the last few years failing to get over them."},
  {text: "it’s my younger siblings wedding and my mother won’t shut up about how i’m going to die alone"},
  {text: "i need a date so i’m hiring you off craigslist, please don’t be a serial killer"},
  {text: "wow i never knew bride/groom had such a hot sibling"},
  {text: "our parents are getting married, and it’s a little weird, but you’re really hot"},
  {text: "you're the dj/wedding singer at my friends wedding and you just played my song."},
  {text: "i’m really drunk, please help me get safely out of the way so i don’t ruin my friends wedding."},
  {text: "our weirdo friends are throwing a wedding for their dogs and we both got dragged along."},
  {text: "i’m stuck at this stupid wedding, so please bartender keep the drinks coming"},
  {text: "they said ‘speak now or forever hold your peace’ so i’m speaking up"},
  {text: "i’m a runaway bride/groom and you’re driving my getaway car"},
  {text: "my bride/groom ditched me at the altar, but fuck them i’m taking this honeymoon anyway."},
  {text: "it’s our honeymoon but we’re spies/secret agents/whatever and bad guys keep appearing to ruin everything."},
  {text: "we’re planning a mutual friend’s wedding"},
  #frozen in time (-7, id 7)
  {text: "i’m a immortal who just woke up from a ‘nap’ what the fuck is this what the fuck is that "},
  
])