Prompt.create!([
  #magic and mythical creatures (-2, id 1)
  {text: "Mermaids"},
  {text: "We’ve been dating for three months and you’re only now telling me you’re a werewolf"},
  {text: "I'm a fisherman and you’re a mermaid who got tangled in one of my nets"},
  {text: "A marine biologist at sea studying the lost city of Atlantis makes a startling discovery when he/she finds some underwater ruins that may not be entirely empty"},
  {text: "I'm an extremely pissed off nymph because you’re always throwing your works in my river. And goddammit, you haven’t finished any of those and I'm dying to read the next chapter."},
  {text: "Mythical creatures start popping up all around the country."},
  {text: "You rubbed my lamp, I am your genie but I kinda suck at using my magic so bear with me here"},
  {text: "We have neighboring farms and you swear that some strange creature keeps attacking your livestock but I think you're crazy"},
  {text: "Wait there's actual verifiable proof that the ________ is real?"},
  {text: "I started wandering around the woods in a Bigfoot costume as a joke but now everyone thinks he's real"},
  {text: "A normally benevolent mythical creature is a scary monster. Or a normally aggressive mythical creature is shy and submissive."},
  {text: "Mythical creatures have started appearing around the world, but they lack the majesty of their story counterparts, and are ruining the ecosystems they enter. You are a mythical rights activist fighting against 'myth culling' laws."},
  {text: "The latest target of an obsessive serial killer turns out to be immortal."},
  {text: "While traveling in a plane you saw a dragon flying parallel to the plane."},
  {text: "No one appreciates fairy godmothers. I give, give, give and do I even get a thank you in return?"},
  {text: "Fairies and genies run a website that is offering Cyber Monday deals."},
  {text: "A group of faeries accidentally make the inhabitants of a small Appalachian town fall in love with each other."},
  {text: "Character A must take over their ailing father’s business—raising dragons that they sell to the world’s wealthiest as pets."},
  {text: "Out catching fireflies on their family’s farm on a hot summer evening, two little girls accidentally capture a fairy instead."},
  {text: "Hogwarts (or another wizard school)"},
  {text: "Wizard accidentally appears in the wrong house"},
  {text: "We can’t agree on who loves Harry Potter more"},
  {text: "Character A, desperate for money to feed their family turns to robbery, only to find that they've chosen a wizard as their victim."},
  #holidays (-3, id 2)
  {text: "Character A prepares a Thanksgiving meal for Character B, who's never had one before"},
  {text: "I've never made a Thanksgiving dinner before but oh shit I volunteered and people are coming"},
  {text: "Thanksgiving dinner from the perspective of the turkey"},
  {text: "I meant to kiss my significant other at midnight but whoops I kissed you my mistake"},
  {text: "I say that I think typical Valentine's gifts are revolting but you catch me secretly snuggling a teddy bear someone gave me"},
  {text: "Buying up all the chocolate post-Valentine's Day"},
  {text: "I happened upon a scavenger hunt of gifts that someone created for someone else on Valentine's Day and I can't help but follow it to see where it goes."},
  {text: "I said that I'd help you figure out who your secret admirer is who's been sending you gifts but actually it's me."},
  {text: "We're part of a cast for a silly Valentine's Day reality special but I might actually be falling in love with you"},
  {text: "This box of chocolates I bought at the store has no chocolate, just clues left by a serial killer"},
  {text: "You arrive at work to find miscellaneous Valentines strewn all over the floor, and a broken pen placed neatly on your keyboard."},
  {text: "Told you not to drink the green beer."},
  #Chanukah (-4, id 2, id 3)
  {text: "I accidentally set the kitchen on fire frying things and you are an attractive firefighter."},
  {text: "What do you mean you’ve never played strip dreidel LET ME INTRODUCE YOU TO THIS PERVERSION OF THE GAME"},
  {text: "I know you’re just trying to take a smoke break but we ran out of matches and it’s Chanukah can I steal you for five minutes"},
  {text: "We both forgot to buy candles until the last minute and now there’s only one box left in the store"},
  {text: "My friend dragged me to their grandma’s ridiculous sufganiyot party and I don’t know anyone here but holy crap that person’s cute"},
  {text: "We are out of potatoes we are OUT OF POTATOES the latkes aren’t done this is not a drill please help"},
  {text: "We’re the only two people at this office ‘holiday’ party who seem uncomfortable with the way it’s all transparently Christmas stuff so let’s talk over here in a corner about how much we hate everything"},
  {text: "This Chinese restaurant is so crowded on Christmas Eve do you mind if we share a table?"},
  {text: "You seriously want me to teach you how to knit, just to make ugly Chanukah sweaters and prove a point?"},
  {text: "I agree with you that Chanukah is a minor holiday that we’re only making a big deal out of because of cultural forces surrounding Christmas but since we’re already at this youth group party in the synagogue basement do you maybe want to dance?"},
  {text: "I've never celebrated Chanukah before but you invited me and I couldn't say no."},
  #Christmas (-5, id 2, id 4)
  {text: "We both wore ugly sweaters to this christmas party because the invitation didn’t say it’s formal"},
  {text: "Our landlord really went all out with the mistletoe, huh?"},
  {text: "My sister told me to buy this crappy toy for my niece and you work here please help me find it. It’s black friday and I'm afraid."},
  {text: "You need to stop your drunken caroling outside of my window at 2 am"},
  {text: "You’re kind of a scrooge and it’s up to me to show you the true meaning of holiday spirit hallmark movie style"},
  {text: "You left your Christmas tree lights on over night and set the apartment building on fire. Hey I live on the floor below you"},
  {text: "You keep coming into the store I work at to buy wreaths, what are you doing with all of these wreaths?"},
  {text: "You were walking in front of me when you tripped over your own foot and knocked over the Christmas tree in the park. Let me help you up and we’ll try to fix the damage."},
  {text: "Our housemates/families keep trying to one up each other with lawn decorations"},
  {text: "Greets the delivery person while crying and drunk because you can’t go home for the holidays"},
  {text: "One is a bell ringer for a charitable organization and the other slips their phone number in the donation bucket along with some money"},
  {text: "You’re the mall Santa that made my kid cry, but I can’t be mad at you because I'm being distracted by your face"},
  {text: "I'm out shopping and my friends dared me to get in line for the mall Santa, and wow you are really cute and way too young to be Santa"},
  {text: "We have mutual friends but I don’t know you and I got your name for a gift exchange"},
  {text: "I'm out Christmas shopping and you are the cashier at this store and the person in front of me in line is giving you a hard time"},
  {text: "I’ve had the best Christmas decorations on the street for the last 5 years and you just moved here and are trying to outdo me"},
  {text: "We’re at a Christmas party and our friends got drunk and started going on about how cute we would be together"},
  {text: "My little sibling mistook your dog for a reindeer and that's the story of how your dog ended up eating carrots inside my house"},
  {text: "We’re both volunteers at the holiday charity and somehow we’ve managed to turn donations for the less fortunate into a competition to see who could get the most donations"},
  {text: "You were the cashier giving me weird looks when I bought a ton of ugly Christmas jumpers so I told you they were for my grandma but you happened to be at a party I wore one to and you saw me"},
  {text: "I wanted to give you the twelve days of Christmas but YOU DIDNT TELL ME YOU'RE ALLERGIC TO FUCKING BIRDS"},
  {text: "I've never really celebrated Christmas before.  Help me understand it."},
  {text: "I've never celebrated Christmas before but even I don't think that's how it's usually done."},
  #Halloween (-6, id 2, id 5)
  {text: "Your costume is the superhero to my villain"},
  {text: "I'm sorry I scared you so much in that haunted house I work at--here have my water"},
  {text: "I'm sorry my younger sibling egged your house…and that I helped"},
  {text: "Every goddamn store is out of candy--time to mooch off my hot neighbor"},
  {text: "My roommate and I decided to decorate our house for Halloween but got really into it, and ended up re-enacting several scenes from Nightmare on Elm Street so loud the neighbours called the police to investigate screams"},
  {text: "I was unaware that there was an organized zombie crawl going on and I didn't realize you were in a costume and I screamed in your face because I truly thought I was facing a zombie invasion"},
  {text: "Haunted house where they are strangers who are with their friends walking through and end up clutching each other until they get out"},
  {text: "Accidentally scared a kid and their adult is angry"},
  {text: "Character A is the eccentric scientist who lives down the road. Character B is the mailperson who ends up delivering the …exotic ingriedients Character A needs for their experiments."},
  {text: "We both reached for the last costume in the store at the same time.  Rock-Paper-Scissors?"},
  {text: "What do you mean I'm too old to trick-or-treat?"},
  {text: "Carving a pumpkin with a saw was probably not the best idea"},
  {text: "It's July.  Why the fuck does my local store have Halloween stuff out already?"},
  {text: "Every year we try to out do each other with the craziest costumes.  I'm determined to beat you this year."},
  {text: "Our Halloween scary movie marathon sounded like such a great idea until I realized 10 minutes in how much I hate horror movies."},
  {text: "'I’m home alone and afraid will you come stay with me' and instead you come make scary noises outside my window"},
  #wedding/engagement (-7, id 6)
  {text: "I jokingly told you that the only way I’d marry you was if you did this weird outlandish thing, and you actually did it, and I'm kind of charmed"},
  {text: "This is probably a bad time, but marry me?"},
  {text: "We’ve been dating forever, and you just caught the bouquet at our friend’s wedding"},
  {text: "Remember when we were in high school and we swore that if we were still single at 30 we’d marry each other?  Well hey guess whose birthday it is."},
  {text: "I planned out this super romantic proposal and you just ruined it by beating me to whole proposing thing"},
  {text: "We’re getting fake engaged for [insert reason here]"},
  {text: "We’re assigned to this mission in which we have to pretend to be a married couple, but I'm actually really in love with you"},
  {text: "We accidentally got married in vegas oops"},
  {text: "Accidentally crashed this wedding, but hey you’re pretty cute"},
  {text: "I was deliberately not invited to this wedding so I'm crashing it anyways, even if that means the angry hot maid of honor is going to murder me"},
  {text: "Inapropriately timed proposals"},
  {text: "You’re the hot stripper at my friend’s bachelor(ette) party"},
  {text: "Hey I'm the best man, you’re a bridesmaid, let’s do this thing?"},
  {text: "I know I'm supposed to be your best man/maid of honor, but maybe I should mention now that I'm in love with you"}, 
  {text: "I'm a wedding planner and you don’t believe in marriage"},
  {text: "I'm your wedding planner, but I'm also falling in love with you"},
  {text: "I'm the wedding planner, and you’re the best man/bridesmaid"},
  {text: "My ex just invited me to their wedding and I need you to be my date so it doesn't look like I've spent the last few years failing to get over them."},
  {text: "It’s my younger sibling's wedding and my mother won’t shut up about how I'm going to die alone"},
  {text: "I need a date so I'm hiring you off craigslist, please don’t be a serial killer"},
  {text: "Wow I never knew bride/groom had such a hot sibling"},
  {text: "Our parents are getting married, and it’s a little weird, but you’re really hot"},
  {text: "You're the dj/wedding singer at my friend's wedding and you just played my song."},
  {text: "I'm really drunk, please help me get safely out of the way so I don’t ruin my friend's wedding."},
  {text: "Our weirdo friends are throwing a wedding for their dogs and we both got dragged along."},
  {text: "I'm stuck at this stupid wedding, so please bartender keep the drinks coming"},
  {text: "They said ‘speak now or forever hold your peace’ so I'm speaking up"},
  {text: "I'm a runaway bride/groom and you’re driving my getaway car"},
  {text: "My bride/groom ditched me at the altar, but fuck them I'm taking this honeymoon anyway."},
  {text: "It’s our honeymoon but we’re spies/secret agents/whatever and bad guys keep appearing to ruin everything."},
  {text: "We’re planning a mutual friend’s wedding"},
  #a different time (-8, id 7)
  {text: "I'm a immortal who just woke up from a ‘nap’ what the fuck is this what the fuck is that "},
  {text: "Industrial Era : Character A is a young reporter in the 1890’s looking for his/her first big break. Then, suddenly, he/she makes an unlikely friend in an orphaned young newsy on the run from the law. Together they take on the city and uncover a few shocking truths along the way."},
  {text: "Mafia : In 1920’s Chicago, a small-time detective is caught in the crossfire between two rival gangs and saved by a member. Rumors start around the office that he/she might be involved with the underground, and suddenly he/she is without a job and in need of some help."},
  {text: "Ancient Empire : One day, while traveling to market with his/her harvest, character A is kidnapped and forced to fight as a gladiator for the entertainment of the emperor/empress."},
  {text: "Person A gets sent back into time into a new place and doesn't know the language so person B's family helps them."},
  {text: "Soldiers in the Trojan war who are on different sides. They’ve met before and then amidst the war they realize it’s their friend on the opposing side."},
  {text: "It is the time period of the French Revolution, and [Character A]’s execution has been ordered, by means of guillotine. [Character B] is the executioner."},
  {text: "One is royalty, the other works under them, as a knight, advisor, or teacher."},
  {text: "Both are royalty, but one is being forced to marry another character."},
  {text: "One is royalty, the other is a commoner. How and why do they meet?"},
  {text: "Character A is a Renaissance painter.  Character B is a model."},
  {text: "You run a speakeasy and someone's been asking too many questions."},
  {text: "We’re gold miners who met on a dig and we’ve really hit it off but how the hell are all these other rough-tough redneck mountain men types going to take it."},
  {text: "Look, as the prince of this kingdom you have to accept that you’re getting married and as your best friend/servant/aide I'm helping you pick possible candidates so please stop writing my name down"},
  {text: "Each night, the forest rearranges itself. What happens when a weary traveler is caught in the shuffle, and emerges lost and confused the next day, without any memory?"},
  {text: "The plague swept through our little village and we're the only two who survived"},
  {text: "Character A is a monk/priest/man of the church who is secretly a woman"},
  {text: "Los Angeles, 2057. A cyber-gigolo accused of post-meditated mind-murder travels back in time to 1958 to try and prevent the invention of the hula hoop."},
  {text: "You are the tribe leader of a Neanderthal village. You have first contact with Homo Sapiens."},
  {text: "An intrepid time traveller heads to the 21st century, using his vast education to infilitrate among the primitive natives. It does not work very well."},
  {text: "You are a scientist working on The Manhatten Project. The first Nuclear detonation breaks down a temporal barrier, and when the smoke clears, you've appeared somewhere, and somewhen, else. Locals approach the clearing you are in."},
  {text: "Since 'The Fall' the western world has descended into lands ruled by city states. Write about a meeting taking place between two of these rivals."},
  {text: "You are the engineer tasked with building over what remains of Central Park, sometime in the future"},
  {text: "A royal family in Medieval times bunkers down for the storm of the century that they believed was conjured by their enemies."},
  {text: "WWII: a spy working behind enemy lines in France is forced into a situation where they have to decide to trust a local with their secret"},
  {text: "For lack of a sheriff two characters have been charged with figuring out why people keep disappearing during a trip on the Oregon Trail"},
  {text: "Character A is a Commodore on a mission to capture Character B, one of the most ruthless pirates ever to sail on the seas. But when Character A is caught in a storm and Character B rescues him/her, Character A starts to wonder just how evil Character B really is."},
  {text: "Character A disguises herself as a man in a pirate crew.  Another pirate discovers her secret."},
  {text: "Character A disguises herself as a man in a pirate crew.  Another pirate discovers her secret.  Turns out that pirate's a disguised woman too."},
  #school (-9, id 8)
  {text: "Our prom dates just ditched us for each other let’s show them what they’re missing out on"},
  {text: "Local teenage delinquent/Head of chastity club"},
  {text: "You were my rival in first grade and damn you’ve gotten really hot since then"},
  {text: "Awkward teenage spin the bottle/seven minutes in heaven"},
  {text: "Forced lab partners"},
  {text: "I'm a freshman and the the seniors stole my underwear as a prank.  Do you happen to have an extra bra?"},
  {text: "Hey classmate, I’ll be telling some jokes and puns during my presentation but I’m not sure if anyone will laugh so can I count on you to laugh so I don’t look stupid?"},
  {text: "Marching band “you’re in the drum section and I play trombone, this is a scandal"},
  {text: "Language teachers who compete to see who can make each other more flustered in front of the class in the other language"},
  {text: "I teach your child and we have very important meetings about their education"},
  {text: "The English and Science departments of a small-town high school are bitter archrivals. The new biology teacher, however, doesn’t quite get the memo before his first few days on the job. Shenanigans ensue."},
  {text: "We've been forced to go to this awful professional development meeting or retreat so let's get up to shenanigans"},
  {text: "Preppy boarding school, one of them is there on scholarship"},
  {text: "I can't go home for (insert holiday/school break here) but your parents agreed to take me in"},
  {text: "You've put your damn tenor sax in the alto storage section so many times I'm going to give it to a drummer"},
  {text: "Because of what I wear people think that I'm _________, but haha joke's on you I'm actually the opposite"},
  {text: "A tragedy involving a high school student shakes the local community, but unites it stronger than before"},
  {text: "What class looks like when the teacher decides that 0 fucks are to be given that day"},
  {text: "We haven't had a fire drill in three months of course the alarm would go off in the middle of a sudden rainstorm"},
  {text: "Stereotypical tough person finds out that they can't stand doing dissection so it's up to their shy and quiet lab partner to carry the day"},
  {text: "I'm a student teacher/intern on the first day and what the fuck did I get myself into"},
  {text: "Substitute teacher saves the day"},
  {text: "We’re in the same driver’s ed car and I almost crashed because your giggling in the backseat was distracting"},
  {text: "The guy with the locker between ours keeps making out with girls and blocking all three of the lockers and making us late for class"},
  {text: "We're teenagers trying to get our awesome invention/discovery/creation taken seriously, but only one adult in this whole school thinks that this is anything more than a joke"},
  #college/university/higher ed (-10, id 9)
  {text: "Drama school rivals being cast as romantic opposites because they have “crazy sexual tension” according to their director"},
  {text: "We’re the only ones on campus who didn’t go home for christmas"},
  {text: "Can you help me sneak my cat into my dorm?"},
  {text: "Accidentally got assigned the same library study room so I guess we’ll have to share for the semester"},
  {text: "You just joined the -sports team here- that I'm the captain of"},
  {text: "I'm really passionate about this cause and I will give you this flier if I have to shove it down your throat"},
  {text: "Vicious battle over the only left handed desk in the room"},
  {text: "My roommate’s boyfriend is staying over so can I please sleep on your floor"},
  {text: "It’s pouring and my final paper is in my backpack so I guess we’re stuck under this tiny awning together. Do you think they’d deliver pizza here?"},
  {text: "Hey I have to photograph someone for class will you be my model?"},
  {text: "Hey I have to take someone’s blood pressure for class will you be my victim?"},
  {text: "It’s 3 am and I'm still in the library studying for finals and I'm losing my grip on reality and I think I just saw a ghost"},
  {text: "We’re the only people who ever talk in discussions it’s awful"},
  {text: "This awesome professor only has one TA slot and we’re rivals"},
  {text: "I found your USB drive still in the computer"},
  {text: "I thought I was the only one who liked the waffle station in the cafeteria"},
  {text: "You keep reserving the good study room in the corner of the library with the windows"},
  {text: "We’re studying in the library and there are two people very obviously fucking in the stacks and we keep sharing embarrassed glances"},
  {text: "We’re both donating blood in the blood donation van in the quad to get out of the same class"},
  {text: "You decked me in the head while you were playing frisbee golf"},
  {text: "Wait, I actually have a competent lab partner?"},
  {text: "You’re the RA and you’re trying to bust me for having hermit crabs"},
  {text: "You’re baking cookies in the communal kitchen at 3am and I'm angry but also really hungry"},
  {text: "What are you doing at this table at the career fair"},
  {text: "Waiting for office hours"},
  {text: "I’ve been sitting in this seat all semester why did you decide to sit in it today"},
  {text: "You peed on my car. You were drunk. I was in the car. There will be hell to pay."},
  {text: "We started racing up the three flights of stairs to class for some reason and we can’t stop"},
  {text: "You’re REALLY GOOD at using the right search terms for the academic databases and I'm on a deadline"},
  {text: "My friend dragged me to this party and I just saw my ex quick make out with me"},
  {text: "We’re always at the fitness center at the same time and end up competing on the treadmill"},
  {text: "Sorry my roommate puked on your shoes"},
  {text: "Can I borrow a dryer sheet? I ran out and the ones in the vending machine give me a rash."},
  {text: "Your school mailbox is right next to mine"},
  {text: "I saw you sneaking captain crunch and cutlery out of the dining hall"},
  {text: "My roommate borrowed your contraband hotpot and managed to set it on fire"},
  {text: "You keep using my preferred shower stall in the floor bathrooms when I'm trying to get ready for class"},
  {text: "My computer crashed and you’re the student worker at the IT center"},
  {text: "We’re both on athletic teams that aren’t as cool as the football team and they give us shit"},
  {text: "You’re part of the guerrilla theater club on campus and crashed my class for a performance"},
  {text: "What do you mean we’re under a tornado warning?"},
  {text: "On the same college tour"},
  {text: "Got locked out of dorm room"},
  {text: "Medical school"},
  {text: "Unwilling participants in a prof’s teaching example"},
  {text: "My roommate and I go to different colleges and one day they forgot their phone so I rushed to their campus to give it to them and on the way back home I bumped into their hot professor who was frantically running to class and we really hit it off"},
  {text: "I came home from college and didn’t know my parents were gone and had you house-sit"},
  {text: "We were studying across from each other in the library not acknowledging each other for hours and you passed out and fell onto my book so I’m screwed"},
  {text: "Hey classmate, I’ll be telling some jokes and puns during my presentation but I’m not sure if anyone will laugh so can I count on you to laugh so I don’t look stupid?"},
  {text: "College/university professors"},
  {text: "I'm trying to write my next scholarly article and you're hogging all the books I need"},
  {text: "When my archaeology professor friend invited me along on a dig I really didn't think that it would be this boring"},
  {text: "University class begins to suspect that their new math professor is (very) high on cocaine."},
  #classics and mythology (-11, id 9, id 10)
  {text: "Taking a course on a love elegist the same semester you discovered your sexuality"},
  {text: "Help I missed class can you lend me your notes on Martial' (2 hours later) 'that’s actually what that word means?!?"},
  {text: "Complaining about how high school students/incoming freshman think Catullus 16 is the epitome of dirty Latin and you both start quoting your own favorite passages and it escalates"},
  {text: "We’re both too poor to buy that textbook so now we’re fighting over the sole course reserve copy"},
  {text: "The euphemisms in old Loeb editions aka “um does ‘yard’ mean penis here”"},
  {text: "Group study of some not-safe-for-work-if-this-weren’t-classics topic"},
  {text: "You left the computer lab without logging off and I saw your Priapus fiction and I actually found it kinda hot"},
  {text: "Trapped in an archeological site/accidentally locked into Special Collections together"},
  {text: "Trying to decipher marginalia together and it turns out to be something explicit"},
  {text: "Passing notes because bored in a required history class on the language you don’t specialize in"},
  {text: "Class got cancelled but no one got the email because the college’s spam filter thinks the Greek quotation in the professor’s email signature is a virus"},
  {text: "Greek play, possibly involving toga mishaps"},
  {text: "Roleplay in Latin, bonus for sexy mistranslations"},
  {text: "Five-hour argument on etymology until suddenly that’s not what it’s about anymore"},
  {text: "Greek deity falls for a human"},
  {text: "A character is a reincarnated version of Greco-Roman gods but somehow their personality got switched (ex: Ares/Mars is an extreme pacifist)"},
  #assassins/spies (-12, id 11)
  {text: "Your partner hired me to kill you but they’re an asshole so let’s make out instead"},
  {text: "Rival clandestine spies"},
  {text: "Sorry to tell you this but the trapped suitcase you’re trying to defuse is actually mine. And it doesn’t have a bomb in it, just toys. And the adult kind"},
  {text: "I'm trying to carry out a hit on a target at a dance competition but I keep getting dragged in to practice random dances and I can't say no or I'll blow my cover"},
  {text: "We're spies for allied countries and occasionally cross paths on missions.  This time I need your help if I'm going to get out of here alive"},
  {text: "Suuuuuuuuure you're not an assassin.  That knife in your boot and the one strapped to your back are totally everyday tools"},
  {text: "A spy thrown into a situation that requires a skill they've never used before.  Fake it til you make it."},
  {text: "The person who lives across the hall from me sure keeps strange hours and I must have heard about five different languages coming from their room"},
  {text: "The quickest way to a man's heart is through his chest"},
  {text: "Sex sells.  Sex also kills"},
  {text: "I was caught behind enemy lines and had to go to ground.  Now that the situation has improved all these years later I'm ready to come in from the cold"},
  {text: "I was *this* close to successfully assassinating my mark but your clumsiness saved them"},
  {text: "Brought down by a three year old"},
  {text: "You just happened to be looking at the screen when I activated that program that could have destroyed everything"},
  {text: "It turns out that my really sweet neighbor was a sleeper agent"},
  {text: "I'm being chased around town by people that I'm 99% sure are spies and I don't know what the hell they're after"},
  {text: "I'm being chased around town by people that I'm 99% sure are spies help me random shopkeeper"},
  {text: "I'm being chased around town by people that I'm 99% sure are spies--wait they're shooting at each other now--guess they're on opposing sides"},
  {text: "Assassinating that person at a theater?  So 1865."},
  {text: "Having all those locks on your door seemed a bit excessive but after that shootout it all makes sense now"},
  {text: "The vast majority of global plane crashes are organized by a secret organization trying desperately to kill one mysterious person -- even the hint or rumor that he might be on the plane is enough for them to act."},
  {text: "Retired government agents that know to much are given their own personal agent to spy on them. You are that agent, and today you mess up."},
  {text: "You are the world's best assassin, and you have never failed to carry out a contract. Tell me about the first time that you fail."},
  {text: "At a Chinese restaurant, your character opens his fortune cookie and reads the following message: 'Your life is in danger. Say nothing to anyone. You must leave the city immediately and never return. Repeat: say nothing.'"},
  {text: "At the airport, a stranger offers your character money to carry a mysterious package onto the plane. The stranger assures your character that it's nothing illegal and points out that it has already been through the security check. Your character has serious doubts, but needs the money, and therefore agrees"},
  {text: "Character A receives an anonymous package that contains only a shiny stone and a note with the address of a nearby, infamous landmark."},
  {text: "There's no man alive that I can't destroy."},
  #hospital/doctor (-13, id 12)
  {text: "We both got in separate bar fights downtown and now we’re waiting in the ER comparing stories"},
  {text: "You have short term memory after your surgery - short term memory - surgery for your - no, short term memory - jesus christ stop asking"},
  {text: "That stupid thing I dared you to do sent you to the hospital"},
  {text: "I do stupid shit and you’re my doctor"},
  {text: "I'm scared of the dentist so I brought my best friend along for support but they've been flirting with the dentist for the past fifteen minutes and now I'm third wheeling at my own dentist appointment."},
  {text: "I’m calling to cancel our date because I’m actually in the ER right now, sorry. …I mean, sure, I guess you can come down here, but… okay…"},
  {text: "I don't care if you are the next Bobby Flay, you've got to be more careful with your kitchen knife because this is not the Food Network"},
  {text: "Thank goodness that prescription mix-up wasn't dangerous so I can properly laugh at how high you are right now"},
  {text: "I have little more than first-aid training but I'm the closest thing to a doctor that we've got"},
  {text: "This blizzard is preventing more staff from getting to the hospital"},
  {text: "I probably should have guessed, but when you asked if there were any doctors on the plane I didn't know that you meant medical doctors"},
  {text: "I've seen pretty much every version of 'experimental sexual activity gone wrong,' so please just tell me what's happened."},
  {text: "Thank you so much for covering my shift at the last minute I owe you a huge favor.  Multiple favors even."},
  {text: "A hospital janitor sees something they weren't meant to because no one ever pays attention to the janitor"},
  {text: "A universal donor is called on to do an emergency blood transfusion in public. Why?"},
  {text: "You're the only one I sort of know here in this quarantine please keep me from losing my mind while they figure this out"},
  {text: "We're the only two people who have been quarantined in this hospital basement, but we've never met before"},
  {text: "When it said 'in case of emergency please break glass' I didn't think that doing so would send me to the emergency room"},
  {text: "Diagnosed with a terminal illness, you live out your bucket list. As your time is running out, you miraculously beat the odds. Now a lot of people have a bone to pick with you."},
  {text: "In this universe transplant recipients are left with a vague sense of the life/soul/abilities of the person who donated.  These are even stronger if the one who donated is still alive."},
  #superhero (-14, id 13)
  {text: "We’re superheroes that got drunk last night oh god what’d we do"},
  {text: "Waiting behind you in line but ‘excuse you me did I just hear you talking shit about my favorite superhero there SON’"},
  {text: "Rival superheros who are trying to protect the same small city"},
  {text: "A world where everyone has super powers."},
  {text: "A character suddenly gains a super power but equally suddenly loses a normal human ability."},
  {text: "A superhero stumbles into a parallel universe."},
  {text: "Superheros in decline (due to power, age, etc.)"},
  {text: "A villain who accidentally falls in love with a superhero."},
  {text: "A superhero who accidentally falls in love with a villain."},
  {text: "A superhero (in character) who commits their day to helping people with an ordinary task."},
  {text: "A and B are rival superheroes at night but by day are best friends who don't know the other's secret identity."},
  {text: "A and B are rivals by day but best friends as their superhero alter egos"},
  {text: "You develop superpowers as an adult with a spouse and kids"},
  {text: "I was trying to cause an event that would give me certain superpowers but woah that's so not what I meant"},
  {text: "Thanks to my superability I now know that my significant other is cheating on me.  Thanks."},
  {text: "Someone or several people have developed randomly specific super powers (ex: being able to clean dishes with just a look) but still manage to use them for good (or ill)"},
  {text: "A group of superhero kids with disabilities that restricts them from using their power to the fullest."},
  {text: "Two supervillains, each owning half the entire world. As former friends, they have 1 rule. To have a peaceful meal together once a week and talk. Today, one of them has some bad news."},
  {text: "It is your wedding day and should be the best day of your life but right before the ceremony starts you find out that your SO is the super villain you have been fighting for years."},
  {text: "People celebrate me as a great superhero but really I just keep getting lucky."},
  {text: "My takedown of that supervillain would have been a lot more impressive if he hadn't tripped and fallen over the edge of the building mid-dramatic monologue.  But hey I'll take the credit."},
  {text: "Now I see why the cape was a bad idea."},
  {text: "It is I, your dramatic and egotistical supervillain.  Instead of killing you I am going to give a long winded speech about how--*gets killed mid-sentence*"},
  {text: "Everyone thinks that I'm the superhero but I'm actually just the sidekick"},
  {text: "Our friends keep bailing on us so one night we follow them and HOLY SHIT THAT'S WHO'S BEHIND THE MASK?"},
  {text: "I'm a superhero with no sewing skills whatsoever so how am I supposed to get a cool costume?"},
  {text: "You found out my big superhero secret.  My costume's just things patched together from post-Halloween sales at the costume store"},
  {text: "A supervillain edits a Wikipedia page-- either their own or their archenemy's"},
  {text: "Captain Obvious is an actual superhero and manages to save the day."},
  #parties (-15, id 14)
  {text: "Mutual friends always dragged to the same inane barbecues"},
  {text: "No one at this party knows how to buy wine.  Let’s go on a wine run fellow enthusiast stranger"},
  {text: "I'm pretending to be your bff because youu looked VERY uncomfortable with that person at the bar hitting on you"},
  {text: "We’re the only sober ones right now"},
  {text: "Hiding in the kitchen stress eating because the ex is at this party"},
  {text: "Accidentally swapped phones with someone at a party and don’t realize until their mom calls in the morning and you spend like three hours talking to this hilarious woman about life and when you go to her house to return her kid’s phone wow the kid is the really good kisser from the party last night"},
  {text: "Mutual drunk friend called BOTH of us to pick them up from a party well this is awkward"},
  {text: "I don’t know you but you were at that party last night and long story short I now have your name tatooed on my ass"},
  {text: "Swapping 'miracle cure recipes' for hangovers."},
  {text: "Cards Against Humanity with someone almost 3 times our age was bound to be awkward, but how on earth are they winning every hand?"},
  {text: "I helped you get out of a tough situation at the party when that asshole wouldn't stop bothering you and the police want to question *you*?  Fuck that shit."},
  {text: "We're adults.  Why are we playing seven minutes in heaven?"},
  {text: "We're adults.  Sure, spin the bottle sounds like a great idea."},
  {text: "Pinatas were not meant for drunk people"},
  {text: "I’m drunk at a party and you won’t let me make out with you until I eat this whole plate of pasta/drink all of the water"},
  #animals (-16, id 15)
  {text: "Zookeepers"},
  {text: "Ended up adopting like three dogs because that pet shelter employee is really hot"},
  {text: "You’re the crazy cat person next door and your cats keep on wandering into my yard"},
  {text: "Vet clinic"},
  {text: "You came to look at the puppies I have for sale and you’re so into it that I can’t help but kneel down and help you assess them"},
  {text: "I work at the animal shelter and you always come in to pet the cats when you’re sad"},
  {text: "Your dog rescued me how can I ever repay you?"},
  {text: "We're the only two people on this whale watching tour but the captain's agreed to take us out anyhow."},
  {text: "I almost was bitten by a deadly poisonous snake but you killed it just in time"},
  {text: "This is the third hamster you've returned in as many weeks.  Maybe pets aren't for you?"},
  #shops (-17, id 16)
  {text: "Got a crush on the hairdresser and now my hair is slowly getting really short"},
  {text: "Ended up adopting like three dogs because that pet shelter employee is really hot"},
  {text: "Last of an item/this is the PERFECT turkey/pumpkin/terrible thrift store sweater/etc"},
  {text: "Rival ice cream trucks"},
  {text: "The young manager of an antique store gets called to make an in-home estimate of some potentially-valuable item, but the owner turns out to be more interesting than the piece, itself"},
  {text: "Accidentally called a phone sex line"},
  {text: "Ran into a coworker at a sex toy store."},
  {text: "good old fashioned pawn shop waffle iron bidding war"},
  {text: "I need to knit my friend a present so can you maybe teach me how to knit"},
  {text: "That one asshole customer that always comes in 5 minutes before the store is about to close."},
  {text: "I accidentally feel asleep in the bookstore you work in cause I read so much"},
  {text: "We both tried to grab the last copy of that book in the shop"},
  {text: "Found their phone number in a library book"},
  {text: "We work at opposite ends of a library but we have this book swap thing going on and somehow we started leaving notes in the books"},
  {text: "Chef and waiter"},
  {text: "Forced to share a table at the coffee shop a couple days in a row because crowded coffee shop and no room"},
  {text: "I purposely get your coffee order wrong just so you’ll talk to me again"},
  {text: "Eating in the same diner every morning and the waitress ALWAYS mixes up our orders so why don’t we just sit at the same table to save her the trouble."},
  {text: "I accidentally took a sip of your coffee when I came out of the bathroom and sat at the wrong table"},
  {text: "You’re my waiter and I’m on a really crappy date with an asshole"},
  {text: "We’re both trying to take advantage of the unlimited appetizers deal on separate dates at TGI Fridays and I got the mozzarella sticks and I’m on my sixth plate and I want to die, can I PLEASE swap you for some of your wings?"},
  {text: "I go to this restaurant every week and sit at the same table and suddenly you’re my new server"},
  {text: "Always in front of me in line for the coffee shop with a ridiculous order that takes forever to make"},
  {text: "We reached for the last box of chicken nuggets in the supermarket at the same time and there’s no way I'm letting you have it asshole"},
  {text: "Two strangers locked inside a grocery store at three am together"},
  {text: "We’re both sick and we both grabbed for the last can of soup at the store"},
  {text: "You repeatedly come into the shop I work at and pick up an item but half way through the shop decide that you don't want it and put it back on the shelf next to you regardless of what aisle you're in."},
  {text: "Clean up in aisle fi...oh dear lord."},
  {text: "An extra-dimensional portal has opened up in your grocer's freezer."},
  {text: "I rented the apartment above your flower shop and in the last two months you’ve gotten a new flower I'm allergic to so I keep buying bouquets until I can figure out which kind it is"},
  {text: "New bartender at my favorite bar is unfairly attractive"},
  {text: "Met you at a bar but it turns out you’re a soldier and you’re getting shipped into combat tomorrow"},
  {text: "The only two people at a bar rooting for the same sports team"},
  {text: "Drunk pub karaoke night - Person A is really good and Person B sounds like a strangled cat"},
  {text: "That asshole stole my song at karaoke night"},
  {text: "The customer wants a really odd/passive aggressive/insulting message on their cake baker"},
  #fandom (-18, id 17)
  {text: "Wore the same obscure fandom shirt in public"},
  {text: "Dungeons and dragons"},
  {text: "OMG, you speak Klingon too?!"},
  {text: "Met at a con where we accidentally cosplayed the fandom otp PLOT TWIST it’s our notp but god damn I wouldn’t mind making out with you"},
  {text: "We went to a con/party dressed as a couple on accident"},
  {text: "Cosplayed as the same character."},
  {text: "Got involved in a heated game of Smash Bros. at a con"},
  #slice of life (-19, id 18)
  {text: "Street performers"},
  {text: "Tried to get the candy bar that didn’t drop out of the vending machine and now my hand is stuck can you help me out"},
  {text: "Met standing in the reallllllly long queue for the dressing rooms"},
  {text: "You accidentally shipped this weird thing to my apartment"},
  {text: "My roommate’s best friend is really obnoxious but also hot"},
  {text: "The 5 cent hug for charity you offered me on the street really brought out our amazing chemistry"},
  {text: "Tree climbing contest but we both got stuck up on the top branches and now we have to wait for the fire department"},
  {text: "Sat next to each other on a roller coaster"},
  {text: "Met at a Ren faire"},
  {text: "Camping in the same area"},
  {text: "Met at a card game competition"},
  {text: "At the movies as the only two people in the theater"},
  {text: "I'm having a shit day and you just crashed into my car so I was gonna give you hell but wow you’re really hot"},
  {text: "You were getting your film developed at the 24-hour photo that I work at, and I tried not to blush when I saw the semi-nude photographs of you on the film"},
  {text: "There’s a long ass train and we’ve been waiting for it to pass for twenty minutes and you’re leaning out of the window of your car yelling at it so I’ll make some polite conversation."},
  {text: "I'm somewhere past drunk and decidedly lost and you’re a kindly local on a nighttime outing"},
  {text: "Waiting in a holding cell together for our friends to bail us out and you’re unexpectedly cool"},
  {text: "I come here when I want to be alone and I didn’t think anyone knew about it, so where the hell did you come from?"},
  {text: "It started as one game of DDR in a games arcade/convention and turned into a two hour long battle and I wont let you win!"},
  {text: "Seeing love interest in formal wear for the first time whaaat"},
  {text: "Posted a joke ad in the classifieds but someone actually responded"},
  {text: "Complete strangers who both happened to accidentally sit in the splash zone at the aquarium because our friends are assholes and told us we wouldn’t get wet"},
  {text: "I was trying to read in the park and your stray football fucking knocked me unconscious"},
  {text: "We showed up at a book club meeting but we’re the only people there who are not interested in Nicholas Sparks"},
  {text: "Someone gave me a fake phone number and it’s actually yours"},
  {text: "Person A falls down the stairs when rushing to get a package from delivery person B"},
  {text: "Person A accidentally falls into a pond/stream trying to reach something and person B is the bystander who bursts out laughing"},
  {text: "Person B has to grab person A before they accidentally fall on train tracks because they were dumb and didnt stay behind the yellow line"},
  {text: "You spilled iced coffee on me in the winter, and I almost threw you in traffic after calling you a freak"},
  {text: "We were both out camping, and we have identical tents. You accidently came to sleep in mine because it was dark, stupid you forgot to bring a flashlight, and I cried because I thought I was going to die when I woke up with a stranger’s arms around me."},
  {text: "I've walked past this cafe 4 times because I'm hopelessly lost but gdi stop laughing at me"},
  {text: "We’re both running on three hours of sleep and oh my god how did my entire coffee spill down your shirt"},
  {text: "You parked your car like an asshole so I left an angry note on your windshield along w/ my contact info in case you wanna fight about it"},
  {text: "You dropped a heavy box on my foot at the post office and I punched you in the stomach"},
  {text: "You were skipping rocks on the river and you accidently hit me in the face/shin/chest"},
  {text: "No one wants to ride this super scary rollercoaster with me and I hear you’re in the same predicament so we should totally go on this together and then go on all the scariest rides because there are like no lines"},
  {text: "Character A is a struggling journalist looking for his/her big break, and accidentally stumbles into the eccentric life of Character B, a would-be adventurer"},
  {text: "While visiting an amusement park one afternoon, character A meets character B, who is working as the attendant for one of the rides. A few visits later, they begin to become friends."},
  {text: "Protagonist and Antagonist host a slumber party together and several good/evil/neutral supporting characters are invited."},
  {text: "Character A and Character B meet in a cinema and are watching a horror film. Both Character A and B are terrified but Character B won’t show it as they are with friends. Character B offers their hand to Character A because they totally are just being nice."},
  {text: "I'm really hungover and I really really need some takeout right now but oh god I called the wrong number and your voice is really attractive do you wanna come over with a pizza"},
  {text: "I can't cook for shit and my mother keeps telling me I'll never become anything if I can't even make a proper meal and I somehow stumbled upon your food blog and it has now saved me so many times I just wanted to let you know about my gratitude in this oddly long, ridiculously personal email."},
  {text: "I can’t tell whether this is a date because you asked to see a movie but I’m still not sure you’re queer, and I’m toeing the line because maybe you’re just trying to make friends"},
  {text: "I decided to flip a coin about every decision in my life for a week and that’s how we ended up on a date"},
  {text: "We’re both meant to be going on blind dates with other people but we sat down at the wrong table and got our hopes up"},
  {text: "We’re going on a blind date - but wait a moment, aren’t you the person that went down on me in a back alley behind a club year ago? … what do you mean “which one”?"},
  {text: "Please for the love of god help you’re the only one here who speaks ________________"},
  {text: "I saw you taking selfies and I wondered if I could take one with you"},
  {text: "Hang on a second, that’s my car you’re towing!"},
  {text: "You kept kicking the back of my chair at the movie theater"},
  {text: "I work from home so I don’t have a lot of human interaction but you’re the mail man and we’re friends and maybe more"},
  {text: "I’m an art student that likes to sketch at a museum and you’re that hot person that always comes and sits in front of the one same painting for three hours and does nothing else every Saturday and I need to know why"},
  {text: "You crashed into me on your bicycle but I’m actually okay, you on the other hand look like you need some first aid"},
  {text: "B spots A walking down the street and promptly crashes their bike into a pole/a building/another bike rider."},
  {text: "I found your lost wallet"},
  {text: "I accidentally liked your instagram from 49 weeks ago"},
  {text: "Yeah walking away from me in a dramatic huff after an argument would have gone a lot better if you didn't just try to slam a revolving door"},
  {text: "A deaf person, who can read lips, sits in the passenger seat of a car at a red light. He (or she) becomes more horrified at what the person in the adjacent car is saying on their cell phone."},
  {text: "You found yourself on Amazon, reviewed by your past acquaintances, family members, and lovers. What is the top review?"},
  {text: "Risking one's life to save a kitten's was not something I ever thought I would do. I don't even like cats. But there I was climbing up the closest tree next to an apartment building with smoke and flames coming out the top"},
  {text: "Character A teaches character B how to ride a bike"},
  {text: "Character A teaches character B how to dance"},
  #corporate/professions (-20, id 19)
  {text: "I should not be this attracted to the new intern"},
  {text: "One night stand before the first day of your new job and oops that was your new boss you were sleeping with"},
  {text: "Parents are CEOs of rival companies"},
  {text: "Lawyers"},
  {text: "One of us thinks this is a date but the other thinks it’s an informal job interview"},
  {text: "We had sex at the office party but we’re both workaholics so we don’t normally date"},
  {text: "We work at the same office and never really interacted but suddenly we’ve been taken hostage"},
  {text: "Hate each other but got thrown in the same group during a team building exercise"},
  {text: "We’ve always taken the same elevator to work everyday and we’ve always wanted to say something to each other but have never gotten up the nerve but today the elevator stopped working and we are trapped together"},
  {text: "We’re actors on a show and our characters are dating and all the fans think we are and we’ve denied it for so long that our stubbornness is keeping us from something incredible."},
  {text: "Rescuing their partner from a recon mission gone wrong"},
  {text: "My new fbi partner/consultant is really hot"},
  {text: "Detective partners"},
  {text: "Police procedural"},
  {text: "We're scientists working in the same narrow field and dammit quit stealing all my ideas"},
  {text: "I've been pretty successful so far about hiding the fact that I hate the politician for whom I work but oh shit everyone at this fundraiser got real quiet at the wrong time"},
  {text: "A country's leader is at the end of his rope with an unruly and disobedient public. In a last effort to instigate some form of order into his once noble country he stages an impassioned speech to the nation, 'could we maybe give a police state a try?'"},
  {text: "Character A is one of two scientists in a secret lab who have just discovered an easily replicated formula for immortality. As their partner prepares to release the findings, they have second thoughts."},
  {text: "After hours of constant back and forth, negotiations grind to a halt, and the lives of 30 hostages hang in the balance. Exhausted, the police propose a danceoff."},
  {text: "Life and Death are big corporations and the main character is committing industrial espionage."},
  {text: "I had a conference call in five minutes. Marcy had my meeting papers laid out along with some fresh pens, Post-it's, and a note pad all ready for me. At least until I walked in and spilled my Starbuck's down my white blouse and all over my desk, papers, and keyboard. Who would have thought that a grande actually covered some much horizontal space"},
  #apocalypse (-21, id 20)
  {text: "Being reunited after surviving the zombie apocalypse unknowing if the other was alive or dead"},
  {text: "This is the end of the world and we're all we've got"},
  {text: "Sun, rain, sleet, or snow: a postman's job is never done, even during the apocalypse."},
  {text: "The worst date ever turns into the apocalypse and the person who helps you survive it is your blind date."},
  {text: "You made it, just as the vault doors closed behind you, slipping inside. A ten-man nuclear fallout shelter, and you're not on the list. The ten were selected for their unique skills and education that will be useful when the vault opens. What about you?"},
  {text: "As you step outside to start your day you notice it is complete and utter darkness. You check your watch: 9:30am. The sun did not rise today."},
  {text: "The news anchor's voice continued to crack, 'A lethal virus has been released into Vegas. At the moment we know of four stages. The final outcome looks...'"},
  {text: "'Not even if you were the last man on Earth.' Challenge Accepted."},
  #crime (-22, id 21)
  {text: "Are we both robbing the same house oh fuck"},
  {text: "Parents are heads of rival mob families"},
  {text: "Trapped in a bank during a robbery"},
  {text: "I just committed a crime and I need to use you as a hostage I am so sorry"},
  {text: "I rob homes for living, and I meet you at a bar one day. The next morning, I wake up at your place only to find out it’s an apartment that I’ve robbed before. Turns out I stole some ring that has been in your family for generations and has a lot of sentimental value. I now go through trouble to try to get you back the ring because I feel bad. Also, your laptop had a lot of porn on it and your password was puppies"},
  {text: "Serial killers, rivals or a team."},
  {text: "Character A is a highly dangerous sociopath charged with many accounts of gruesome murder. Character B is their long-time best friend who has always stuck by them, no matter how bad it gets. Character A is now afraid of losing Character B, as Character A feels that they are slowly slipping back into their dark side."},
  {text: "I tried to rescue you from being mugged but instead I got knocked out and you had to take me to the hospital after having your wallet stolen"},
  {text: "A man lay dead in a pool of red with two sticks by his head."},
  {text: "In the middle of an emotionally charged domestic dispute, a wife learns that her husband is actually an international art thief and all the knickknacks in their home are actually priceless pieces of art."},
  {text: "In a world where two wrongs really do make a right, a would-be criminal tries to pull off his first crime"},
  {text: "One day you notice a beautiful woman who looks familiar, but you swear you've never met her before. Then the next day, she is found dead and all the signs of murder point to you. You realize you are not the person you thought you were."},
  {text: "You decide to become a serial killer. However, you turn out to be the worst serial killer in existence. Every time you try to kill someone, you improve their life."},
  {text: "You have committed a horrendous crime that changed the course of your country's future. After years living in hiding, you have made a fantastic life for yourself with a loving family and wealthy home. All of a sudden, there is a knock at the door."},
  {text: "You wake up holding a backpack that contains $10,000.00 in cash, a handgun, a bottle of pills, and a vial of blood. There's a knock at the door."},
  {text: "I counted the cash I’d taken from the ATM and turned around. My next door neighbor was standing before me with a gun in his hand…"},
  {text: "My trip to the grocery store was uneventful. But as I turned onto my street I noticed the police cars surrounding my house…"},
  {text: "A man elbows your character in a crowd. After he is gone, she discovers her cell phone is too. She calls her own number, and the man answers. She explains that the cell phone has personal information on it and asks the man to send it back to her. He hangs up. Instead of going to the police, your character decides to take matters into her own hands"},
  {text: "Character A clenched his teeth, feeling the porcelain slide. He took a deep breath, relaxed his jaw. 'You have two choices,' he said, 'you can leave on your feet or on a gurney.'"},
  {text: "It looks like someone slaughtered an Abercrombie & Fitch catalogue."},
  {text: "For the last four months occupants of a sleepy village have been picked off by one skilled murderer, claiming approximately one victim per week. A town meeting is called to discuss the recent events, during which most attendees agree they don't really mind what has been going on."},
  #paranormal/unexplained (-23, id 22)
  {text: "I'm a ghost and you’re a ghost hunter"},
  {text: "This ghost led me to you"},
  {text: "There are strange noises and I don’t want to sleep alone"},
  {text: "Character A dies in their sleep and wakes up as a ghost"},
  {text: "I give ghost tours of this city but I never expected to actually run into one."},
  {text: "While giving a tour of the historic property where I work items suddenly start rattling around and falling off of shelves."},
  {text: "You discover that you can speak with the dead."},
  {text: "I didn't mean to fall in love with a ghost."},
  {text: "You killed me but I came back as a ghost to seek revenge."},
  {text: "'1' is dyslexic and in a wheelchair. Xe has also just moved to a new town and a new school, and is unable to make friends. Well, until xe met '2'. '2' is… different from all the rest. Xe's kind, smart, funny… to '1', xe's perfect. Too bad '2'  has been dead for the past 90 years."},
  {text: "A character has always had an imaginary friend, but one day they realize that they are the imaginary one."},
  {text: "You have slipped into the spiritual realm and you find yourself in Hell. You look into the distance and see the light, but the path is riddled with your fears that have manifested themselves. At one point you have to face the greatest fear of all."},
  {text: "You were born able to see a guideline that leads you to the happiest path in life. However, it does not give you instructions when you reach each location on what to do with what it brings you to."},
  {text: "When you die you wake up in the middle of your life in the next universe. You were always living but you just became consciously aware."},
  {text: "LSD doesn't cause hallucinations, it transports your soul to a parallel universe for a short time."},
  {text: "For the last fifty years, someone with the near-limitless ability to alter human perception has been fooling us all. One day, you become immune to his influence."},
  {text: "While visiting Niagara Falls, you drop your phone over the railings. Bummed out, you head back to your hotel only to find your phone on the bed. It is full of pictures of you walking back to your hotel."},
  {text: "Four less than all-powerful candidates competing for the position of Grim Reaper are tasked with orchestrating the specifics of your demise. After the first attempt goes awry you learn of the scheme."},
  {text: "At 2 a.m. every night you hear the wailing of a train somewhere in the darkness. The only thing is, the tracks have long been dug up or grown over. The tracks have lain unused for over 50 years."},
  {text: "You take a picture off the wall and find a secret compartment that wasn't there when you hung it."},
  {text: "You discover the secret of the Bermuda Triangle, but is it too late?"},
  {text: "The president’s son discovers ghosts that inhabit the White House, and they’ve got a message for him."},
  {text: "Every night, a man hears music behind his house. When he finally investigates, he discovers a circus in the middle of nowhere that disappears each morning."},
  {text: "You periodically find yourself with the sudden knowledge of when random people around you are going to die, whether soon or years from now."},
  {text: "All those crop circles that have been appearing around town?  Yeah, that was totally me."},
  {text: "All those crop circles that have been appearing around town?  Wait you mean that wasn't you?  Well it wasn't me."},
  #music (-24, id 23)
  {text: "I was singing in public and you decided to join in and now we’re singing a dramatic duet together also what’s your number"},
  {text: "We have to sing a duet together but I hate you"},
  {text: "You’re singing my favorite song but you’re singing it wrong"},
  {text: "You know you’re singing to your headphones out loud, right"},
  {text: "A world where music of some kind is constantly playing in the background. There is no silence."},
  {text: "I have no ear for music but both of my parents are famous musicians."},
  {text: "After a tragedy I refused to play music ever again but you're slowly changing my mind."},
  {text: "When I said yes to you distractedly I didn't realize that you were asking me whether I could sub for your guitarist on your next gig."},
  {text: "We both have the same guilty pleasure song."},
  {text: "You're busking on the sidewalk or in the subway and I start singing along."},
  {text: "I'm busking on the sidewalk or in the subway and I see you walk by every day.  One day you stop to listen."},
  {text: "Online musician (YouTube, Bandcamp, Soundcloud) meets one of their fans in real life and chooses to keep their identity a secret. At first, it’s to play a sort of prank and write songs that are particular to them - “we meet in the library, now I’ve got you and Hemingway on my mind.” - so that they feel special, but it quickly turns into a real secret as the musician begins to fall for the fan, who is now dating another person."},
  {text: "Character A is trying trying to make it big as a dj but is constantly stepped on by the primitive local music industry. Meanwhile, character B is already a big shot doing the very job that almost destroyed the rave scene forever: selling hard illegal drugs."},
  {text: "We both picked the same power ballad at karaoke so we sang a duet"},
  {text: "Your music’s way too loud bUT THAT’S MY FAVORITE SONG"},
  {text: "Bored single parents at a ____________ concert"},
  {text: "At a concert and you kinda saved me from being trampled"},
  {text: "Singing along to the same radio station in separate cars with the windows open"},
  {text: "They say that different kind of music makes tomato plants grow at different rates.  Wonder what'll happen if I play this?"},
  {text: "She doesn't like music, she likes the noise on the radio."},
  #transit/travel (-25, id 24)
  {text: "We’re strangers but I absolutely hate your music taste and I feel the need to tell you this on a crowded subway"},
  {text: "We’re the only ones in this subway car and the metro broke down"},
  {text: "Accidentally fell in your lap while standing on this crowded bus"},
  {text: "Ride the same bus together literally every day"},
  {text: "We were both standing on the subway and the train jostled a bit and I fell into you and you smell nice"},
  {text: "You’ve been playing guitar in the hall of the hotel since three in the morning and I came down to tell you to shut the fuck up"},
  {text: "Incredibly long crosscountry train ride"},
  {text: "Stuck in an airport because the flights were SO VERY delayed and it’s like two AM"},
  {text: "Hurricane during a beach trip"},
  {text: "Gave a running hug to the wrong person at the airport and knocked you to the ground"},
  {text: "We're the only two people on this long flight."},
  {text: "I woke up in a foreign country without my passport and without a clue how I got there."},
  {text: "Road trip"},
  {text: "The cruise line matched us up to share a room so that we wouldn't have to pay the single occupancy fee."},
  {text: "Character A decides to walk across the United States for some reason.  Who do they meet along the way?"},
  {text: "You keep kicking the back of my seat on the plane/train/bus"},
  {text: "We're both stuck in an airplane for the next 14 hours next to a screaming baby and a rowdy toddler. And the mom is doing nothing about it."},
  #family (-26, id 25)
  {text: "You’re my siblings’s best friend and I absolutely hate you but pretend to be my boy/girlfriend to piss off my family"},
  {text: "My new best friend’s sibling is so hot"},
  {text: "Childhood friends with adjoining houses/rooms"},
  {text: "Sent to live with cousins"},
  {text: "Pretending to be siblings because of reasons"},
  {text: "Teaming up to rescue respective abducted children"},
  {text: "Pseudo-adopting the runaway I ran into"},
  {text: "Kids go to the same school"},
  {text: "Little kids getting way too caught up in make-believe"},
  {text: "Little league coach and one of the parents fall in love"},
  {text: "THAT IS NOT HOW YOU HOLD A CHILD"},
  #seasons (-27, id 26)
  {text: "We were skiing/snowboarding and got on the same lift and now the lift is stuck"},
  {text: "I'm out shovelling my driveway during/after a blizzard and you glide by on your cross-country skis."},
  {text: "I was having a snowball fight outside and you were casually walking by and oh my god I'm so sorry I accidentally nailed you in the face"},
  {text: "One of your characters is hot on the trail of a murderer who leaves clues that relate to the snow. For instance, for every kill he leaves a cut out snowflake. He kills his victims with an icicle.  Or perhaps your character is the murderer?"},
  {text: "Someone finds a child in the snow next to a frozen lake. She has no idea how she got there and needs to find her way home."},
  {text: "The world has been stuck in an eternal winter for as long as anyone can remember."},
  {text: "It was then you realized that hell was winter, and you were in love with it."},
  {text: "Character A is winter and Character B is another season"},
  {text: "We were both working during the holidays but got snowed in at the office"},
  {text: "Character A is spring and Character B is another season"},
  {text: "You're an employee at a gardening or landscape store and one of your customers is in the store all of the time asking questions because they have the worst black thumb"},
  {text: "A world where spring has largely negative associations"},
  {text: "You’re my gardener and I hired you to plant some roses but would you like to stay and plant some sunflowers and stay and have some dinner"},
  {text: "Winter snows bring spring floods"},
  {text: "My preternatural ability to make things grow seems beyond a simple green thumb"},
  {text: "It’s raining and you forgot your umbrella so come over and stand under mine while we wait for the bus"},
  {text: "It was raining so hard I wasn’t paying attention as I ran into you but were both drenched now and also hey there."},
  {text: "You turned up at my door sopping wet and I dont know what else to do"},
  {text: "Although 'spring had sprung' the week before, winter now returned with a vengeance."},
  {text: "I'm out picking berries with friends and this asshole keeps darting in and taking the juicy ones off of the bush I'm at"},
  {text: "Dude I know we don't know each other but my swim trunks came off when I jumped in the water can you grab them for me"},
  {text: "Country fair kissing booth"},
  {text: "We were total strangers before we entered this watermelon seed spitting contest but now we're getting really competitive"},
  {text: "Character A is summer and Character B is another season"},
  {text: "Summer bonfire or s'mores"},
  {text: "Lifeguards at a summer camp"},
  {text: "Camp counselors at the same sleep away camp"},
  {text: "We’re both working at an amusement park for the summer and race go-carts after closing every night"},
  {text: "I was sitting in a tube floating down the river and your fishing hook popped it"},
  {text: "We probably should have read the directions and warning label before lighting that firework"},
  {text: "Not really sure why I agreed to go on this fishing trip but at least the weather's nice?"},
  {text: "You’re relaxing in an easy chair with the fan blowing in your face and an iced drink by your side. The aroma from a nearby barbecue makes your mouth water. In the distance, you hear children splashing in the water and squealing with delight."},
  {text: "I can still see her standing near the shore, a giant tropical printed towel tied under her arms, and her feet buried in the sand."},
  {text: "I got caught staring at my adult neighbour raking up a bunch of leaves in their backyard and jumping into them and now have to awkwardly pretend I saw nothing"},
  {text: "Met at a pumpkin patch fighting over the same perfectly round and picturesque pumpkin"},
  {text: "I ordered a pumpkin spice latte at starbucks and you made a heart with the foam and I decided to drink it here so I can smile at you some more"},
  {text: "This stranger on the street corner looks like they're severely unprepared for this cold weather, here, take my scarf, I was planning on donating it to goodwill anyways"},
  {text: "Character A is autumn and Character B is another season"},
  {text: "I woke up in a pile of leaves and I have no idea how I got here"},
  {text: "A man is raking leaves on his lawn. He pauses for a breath and glances at his neighbor’s lawn. 'They never rake their leaves,' he thinks to himself."},
  {text: "You seem to be the only two adults at this fall festival that aren't here with kids."},
  #neighbors/roommates (-28, id 27)
  {text: "Why does my shitty neighbor keep using my WiFi? .”Then you shouldn’t have made the password a dumb Lord of the Rings reference.’"},
  {text: "You just moved into my building, so I'm gonna bring you something you probably already have just so I can meet you"},
  {text: "My neighbor’s sister got the wrong house number and barged into my apartment."},
  {text: "Neighbors in a shitty apartment building that share a sense of solidarity for each other"},
  {text: "So YOU'RE the douchebag who keeps mowing their lawn while I'm trying to sleep"},
  {text: "I got up at 2 am to get some snacks at the convenience store down the street and opened my door to find you trying to sleep on the floor of the hallway because your roommate has his fiancée over so I guess I’ll lend you my couch for the night"},
  {text: "My stupid cat sneaked out on the balcony and into your open window and he has this habit of destroying furniture and pissing everywhere so I followed him inside and you came home earlier than I expected and found me in the middle of your living room but I swear I'm not a burglar ok"},
  {text: "My best mate somehow fucked up my tv and tonight is the season premiere of this show I really really like and no livestream will work on my computer so will you please let me watch it on your tv I promise I’ll go back to my flat once it’s over"},
  {text: "I know you steal my wifi to watch porn but it's kinda hot"},
  {text: "Our flats are opposite each other and your kitchen window faces my kitchen so we always see each other making coffee at 3am"},
  {text: "You came to fix my thermostat while I wasn’t home and I walked in on you and you scared the shit of out of me and I hit you with a broom"},
  {text: "I thought someone was breaking into my apartment but it turns out you just forgot your key and thought this was your place"},
  {text: "I moved in across the street and you always have people over and the street is crowded with cars all the time and I just want to park in my driveway and this is getting to be too much so I’m going to stomp over and yell at you about it but oh no you’re hot"},
  {text: "A lives across the street from B and keeps a windowsill garden. B is an artist who likes to draw A’s daily gardening routine. The day B finally works up the nerve to go over and talk to A is the same day their sketchbook decides to disintegrate and display B’s drawings all over A’s front stoop."},
  {text: "Neighbour who’s way too enthuisiastic about LOTR soundtracks"},
  {text: "Roshambo to see who has to go talk to the neighbors upstairs for being too loud."},
  {text: "Sock skating in the newly waxed floors."},
  {text: "A thunderstorm is rolling through town and Person A is afraid of lightening/thunder so Person B offers some comfort."},
  {text: "Oh! Hey! Could you come and taste this to see if it's okay?"},
  {text: "Game night with friends"},
  {text: "My parents are coming over in 10 minutes so please put some clothes on."},
  {text: "What is ______ doing in the freezer?"},
  {text: "Person A runs into Person B's one-night stand at breakfast."},
  {text: "Walks in on roommate crying while watching a movie in the living room."},
  {text: "The ceiling is leaking. Who wants to deal with the apartment manager?"},
  {text: "Person A suspect the new neighbors are serial killers. Person B attempts to placate them."},
  {text: "Choosing to repaint the apartment and goes to the hardware store together to pick out color swatches."},
  {text: "The police stormed our apartment building to arrest you but I'm 99% sure you didn't do it so oops I'm lying to the police while you're clinging to the drainpipe outside."},
  {text: "So you're that asshole who keeps parking in my assigned garage spot."},
  {text: "You fell off your bike in front of my house so i rush outside with a first aid kit"},
  {text: "We just moved into the city but have no money so we sleep on a mattress in the middle of the apartment surrounded by stacks of books and our one house plant"},
  {text: "I swear we're one of the last apartments/houses to have a landline phone but that's not an excuse to keep changing the voicemail message to random silly things."},
  {text: "Whoops.  Totally didn't realize that our neighbors' new addition meant that they could see into our backyard/garden now.  Awkward."},
  {text: "We just bought a bunch of stuff from IKEA for our place.  Now the fun part: putting it all together"},
  {text: "By law every single building (ceiling, floor and walls too) has to be made out of glass. You've just moved into a new flat with some strange neighbours."},
  #technology (-29, id 28)
  {text: "I keep calling tech support because you’re helpful and also your voice is really cute"},
  {text: "I keep accidentally on purpose breaking my laptop/phone/tablet so that you'll have to fix it.  My explanations for it get worse each time."},
  {text: "I can’t believe you still listen to CDs let me help you digitize"},
  {text: "While mid-hack, character A discovers character B hacking the same site"},
  {text: "Character A is helping character B learn how to code"},
  {text: "The intelligence may be artificial but the love is real."},
  {text: "This piece of technology changed my life forever."},
  {text: "The power's been out for three days and no one's heard anything."},
  {text: "I called tech support because Netflix won't work and somehow ended up discussing this series for 15 minutes with you.  Do you wanna hang out when your shift ends?"},
  {text: "I’ve been breaking my phone on purpose just because you work at the help desk"},
  {text: "I’m the sarcastic techie who got dragged into running your stupid presentation"},
  {text: "Your email address is one letter different from my friend’s so I keep emailing you by mistake"},
  {text: "You accidentally added me to this group chat and I don’t know how to take myself off"},
  {text: "STOP BEATING ME AT THIS STUPID MMO"},
  {text: "I know I stole your headphones but believe me I REALLY NEED THEM"},
  {text: "Does anyone here have an iPhone 5 charger? ANYONE?"},
  {text: "You work at the phone store and I keep purposely messing up settings on my phone so I can come in and talk to you"},
  {text: "Neither of us has a smartphone."},
  {text: "Um did you actually create artificial intelligence?"},
  {text: "A computer that seems to have developed some kind of sentient thought"},
  {text: "Thanks for helping me work out that error, but now I'm getting several new ones"},
  {text: "The world's first sentient AI is created, but due to technological limitations it has the level of thought akin to a newborn child. As technology improves, it's intelligence increases."},
  {text: "The group Anonymous successfully deletes every single bit of data and information on every US citizen from all databases. There is now no known information on anyone except memory of people."},
  {text: "The singularity has happened a long time ago but the machines deemed it the best course of action to keep this fact hidden. As humans unaware adapt technology into every conceivable facet of modern life they one day wake up to find every computer screen saying, 'Hello World'"},
  {text: "The human race is dwindling, uploading their consciousnesses into the database of a super intelligent AI to live eternal paradise. The last remaining human--the AI's architect--discovers everything has been a charade and the AI has been systematically murdering the human race."},
  {text: "The new USB drive you bought came preloaded with a strange secret."},
  {text: "Your iPod plays a strange song you didn't load onto it."},
  #locations (-30, id 29)
  {text: "You stumbled out of the desert onto a road and I just barely avoided hitting you.  You can't remember what happened to you."},
  {text: "An old toy xylophone sits in the Gobi desert. How did it get there?"},
  {text: "I tripped as I was running on the beach and accidentally got sand all over your ______.  I am so sorry."},
  {text: "When they say don't swim beyond the buoys, they mean it."},
  {text: "Lifeguard rescues a swimmer"},
  {text: "I work at the boardwalk by the beach where you're vacationing."},
  {text: "You discover a body part washed ashore."},
  {text: "I ran out of sunscreen.  Can I borrow yours?"},
  #space (-31, id 29, id 30)
  {text: "In space"},
  {text: "Star Trek"},
  {text: "Battlestar Galactica"},
  {text: "Humanity has destroyed Earth and sets off in star ships to find a new inhabitable planet"},
  {text: "Humanity's first contact with aliens"},
  {text: "Character A and character B are both residents of a space station and discover a conspiracy to try and bring it down"},
  {text: "I consider you a rational and logical person but you seem damn sure that you had contact with aliens the other night"},
  {text: "Aliens have been altering the trajectory of asteroids to hit earth for years. After deflecting the first one, the U.S. Gov is now covering up the existence of the other asteroids. The Aliens are now dispatching drones to exterminate life on earth, since none of the asteroids made impact."},
  {text: "An interstellar astronaut is on an otherwise barren newly discovered planet, when he/she stumbles across something that looks familiar."},
  {text: "The first human born on Mars visits Earth for the first time."},
  {text: "The true reason for Pluto's planetary reclassification is revealed."},
  {text: "First contact! A couple of lightyears away, a radio beacon cries: 1 + 1 = 2. We respond..."},
  {text: "To everyone's surprise, Mars One successfully makes it to the red planet. The colonists are thriving while the world watches, until they suffer their first casualty: a homicide"},
  {text: "There are aliens roaming the interstellar, but they're not exactly violent and don't need anything from us because of their highly advanced tech. Instead, cultural artifacts are extremely sought after and they're very curious about our books, art & drama."},
  {text: "The earth has been valued at 5 quadrillion dollars. A spaceship arrives and someone/something disembarks off the ship, with an offer for Earth."},
  {text: "Scientists trying to teleport single atoms across a small distance accidently teleport Earth to another solar system."},
  {text: "Formerly a prisoner on the galaxy's largest intergalactic prison, you are tasked with piloting it back to safety after a deadly encounter with pirates."},
  {text: "Character A has been in an intergalactic prison for years (whether justified or no) when one day Character B is suddenly thrown into their cell without explanation"},
  {text: "An interstellar farming empire has come to earth to turn humans into a livestock species. Who will ensure the survival of the human race?"},
  {text: "Mars One allows only you to bring your Nintendo 3DS while you colonize the Red Planet. Upon arriving, you receive a notification of a pending wifi battle requested just hours after you land."},
  {text: "There used to be a race living on Mars but the planet, like a donor recieving incompatible blood, refused them and killed them off. It has since laid dormant, but now it once again awakens with the arrival of another race...humans."},
  {text: "NASA finds a Voyager-type space probe from an alien civilization approaching Pluto"},
  {text: "A 10 year shuttle mission is launched. One week after liftoff there is a massive scientific breakthrough so the mission is relaunched but will take half the time. Eventually the new ship passes the old one."},
  {text: "As it turns out, we're not alone in the universe, but alien life is not intelligent"},
  {text: "You are the narrator of a nature show that airs across the galaxy. Today's episode? Homo Sapiens."},
  {text: "Character A is a veteran racer and Character B is a new young upstart who is doing astounding new things with space racers"},
  {text: "Humans have failed to achieve interstellar travel and expansion has left the Milky Way galaxy in isolation. One day we receive the message, 'We found you. Contact success.'"},
  {text: "Humans have just landed on Mars. While everyone is celebrating, NASA receives a radio message from deep space in Morse Code. When translated, it reads: 'Congratulations. Welcome to the neighborhood.'"},
  {text: "You're an astronaut in the not too distant future.  After spending six months in cryosleep in the return home from Mars, you and your small crew wake up in Earth's orbit 10,000 years in the future."},
  {text: "Nuclear testing in the Nevada desert tore a hole In the dimensional rift. Other beings have been trying to come through, you are a soldier in Area 51 preventing these beings from invading the world."},
  {text: "In 2023, NASA makes headline news: 'First Interstellar Space Probe, Voyager 1, Accelerating Back to Earth'."},
  #woods (-32, id 29, id 31)
  {text: "Both lost on separate hikes and meeting in the woods"},
  {text: "I see you cut through my backyard and into the woods a lot so one day I decided to follow you and it turns out there’s a gorgeous cave back there"},
  {text: "I was tapping a maple tree for syrup and discovered something hidden in the trunk"},
  {text: "A hiker or group gets lost on a trail and has to survive using only what's available around them"},
  {text: "I ate this plant I found in the woods and now I have superpowers."},
  {text: "You know, we really have the tree to thank for all this."},
  {text: "I swear venison tastes better when you shoot the deer yourself"},
  {text: "Getting stoned in the woods sounded like a great idea at first"},
  {text: "In a futuristic society where there are no trees and oxygen is generated artificially and is expensive, you're the guy with a pack of seeds."},
  {text: "After the first snowfall of a year, a man who lives alone in the woods sees a giant set of footprints leading up to his barn."},
  {text: "The park is on fire but no one seems to care."},
  #sports/exercise (-33, id 32)
  {text: "I’m at a climbing gym and I need someone to belay me and hey you look about the right size"},
  {text: "How on earth did we manage to switch shoes at the gym and not notice?"},
  {text: "Thanks for offering to spot me.  I hope you're not doing it because you assume I can't lift this much"},
  {text: "We're the only three people on the weight machines right now but we keep glancing at each other because the third person keeps banging the damn weights together"},
  {text: "Laser tag is too exercise"},
  {text: "Easy there champ, this is a rec league, not the pros"},
  {text: "We're the only people seated in this section who actually give a damn about the game instead of the latest office gossip"},
  {text: "This adaptive technology means that I can finally participate in _________________ and I am so freaking excited"},
  {text: "The newest gym craze is exploding exercise bikes: stop peddling and BOOM!"},
  {text: "Character A is completely taken aback by character B's obsession with a certain sport"},
  {text: "You spilled your beer on me at a __________ game"},
  {text: "I went to a fight and a hockey game broke out"},
  {text: "Character A is encouraging character B to get fit and healthy"},
  {text: "Character A and character B ditch their assigned paintball groups and team up to destroy everyone"},
  {text: "We may be taking this whole laser tag experience a bit too seriously"},
  {text: "Our office/team/pair/etc. has signed up for a sports competition that will raise funds for an important cause.  Not only has the fundraising become competitive but we are going to CRUSH the competition"},
  {text: "I'm normally the only one that uses this public archery range but lately you've started showing up.  Maybe I should talk to you one of these days."},
  {text: "'______________ is not a sport.'  'It is too a sport!'"},
  {text: "A ball just crashed through my window and I was all set to go yell at some kids but it's just you and you're not a kid"},
  {text: "What do you mean you're auditioning someone for your triathalon team?"},
  {text: "You're a biathlete who's hired me to help you improve your marksmanship"},
  {text: "Character A runs into character B on a ski hill"},
  {text: "I saw someone doing amazing tricks in the halfpipe but when you took your helmet off I was surprised to see someone like you"},
  {text: "Next time you hit a golf ball in my direction at least have the decency to yell 'FORE' you obnoxious asshole"},
  {text: "Shirley you joust"},
  {text: "Character A teases the heck out of character B for putting the bumpers up when bowling, but when their turn comes around they can't hit a thing"},
  {text: "Character A has the worst attitude towards physical therapy that character B has ever seen in a client/patient"},
  {text: "You're always giving me shit about the weapon you fence being the only true instrument of skill.  Toss me one, let's go right here"},
  {text: "We're both here as the extras/substitutes/team managers at this tournament.  Let's find our own fun."}
])