Prompt.create!([
  #mythical creatures (-2, id 1)
  {text: "mermaids"},
  {text: "we’ve been dating for three months and you’re only now telling me you’re a werewolf"},
  {text: "i’m a fisherman and you’re a mermaid who got tangled in one of my nets"},
  #Chanukah (-3, id 2, id 3)
  {text: "I accidentally set the kitchen on fire frying things and you are an attractive firefighter."},
  {text: "What do you mean you’ve never played strip dreidel LET ME INTRODUCE YOU TO THIS PERVERSION OF THE GAME"},
  {text: "I know you’re just trying to take a smoke break but we ran out of matches and it’s Chanukah can I steal you for five minutes"},
  {text: "We both forgot to buy candles until the last minute and now there’s only one box left in the store"},
  {text: "My friend dragged me to their grandma’s ridiculous sufganiyot party and I don’t know anyone here but holy crap that person’s cute"},
  {text: "We are out of potatoes we are OUT OF POTATOES the latkes aren’t done this is not a drill please help"},
  {text: "We’re the only two people at this office ‘holiday’ party who seem uncomfortable with the way it’s all transparently Christmas stuff so let’s talk over here in a corner about how much we hate everything"},
  {text: "This Chinese restaurant is so crowded on Christmas Eve do you mind if we share a table?"},
  {text: "You seriously want me to teach you how to knit, just to make ugly Chanukah sweaters and prove a point?"},
  {text: "I agree with you that Chanukah is a minor holiday that we’re only making a big deal out of because of cultural forces surrounding Christmas but since we’re already at this youth group party in the synagogue basement do you maybe want to dance? :D?"},
  {text: "you were walking in front of me when you tripped over your own foot and knocked over the christmas tree in the park. let me help you up and we’ll try to fix the damage"},  
  #Christmas (-4, id 2, id 4)
  {text: "we both wore ugly sweaters to this christmas party because the invitation didn’t say it’s formal"},
  {text: "our landlord really went all out with the mistletoe, huh?"},
  {text: "my sister told me to buy this crappy toy for my niece and you work here please help me find it. it’s black friday and i’m afraid"},
  {text: "you need to stop your drunken caroling outside of my window at 2 am"},
  {text: "you’re kind of a scrooge and it’s up to me to show you the true meaning of holiday spirit hallmark movie style"},
  {text: "you left your christmas tree lights on over night and set the apartment building on fire. hey i live on the floor below you"},
  {text: "you keep coming into the store i work at to buy wreaths, what are you doing with all of these wreaths?"},
  {text: "you were walking in front of me when you tripped over your own foot and knocked over the christmas tree in the park. let me help you up and we’ll try to fix the damage"},
  {text: "our-housemates/families-keep-trying-to-one-up-each-other-with-lawn-decorations"},
  {text: "greets-the-delivery-person-while-crying-and-drunk-because-you-can’t-go-home-for-the-holidays"},
  #Halloween (-5, id 2, id 5)
  {text: "your costume is the superhero to my villain"},
  {text: "there are strange noises and I don’t want to sleep alone"}, #maybe put this in paranormal instead?
  {text: "I’m sorry I scared you so much in that haunted house I work at; here have my water"},
  {text: "I’m sorry my younger sibling egged your house… and that I helped"},
  {text: "every-goddamn-store-is-out-of-candy-time-to-mooch-off-my-hot-neighbor halloween"},
  {text: "me and my roommate decided to decorate our house for halloween but got really into it, and ended up re-enacting several scenes from nightmare on elm street so loud the neighbours called the police to investigate screams"},
  {text: "i was unaware that there was an organized zombie crawl going on and i didn't realize you were in a costume and i screamed in your face because i truly thought i was facing a zombie invasion"},
  #wedding/engagement (-6, id 6)
  {text: "i jokingly told you that the only way i’d marry you was if you did this weird outlandish thing, and you actually did it, and i’m kind of charmed"},
  {text: "this is probably a bad time, but marry me?"},
  {text: "we’ve been dating forever, and you just caught the bouquet at our friend’s wedding"},
  {text: "remember when we were in high school and we swore that if we were still single at 30 we’d marry each other, well hey guess whose birthday it is"},
  {text: "i planned out this super romantic proposal and you just ruined it by beating me to whole proposing thing"},
  {text: "we’re getting fake engaged for [insert reason here]"},
  {text: "we’re assigned to this mission in which we have to pretend to be a married couple, but i’m actually really in love with you"},
  {text: "we accidentally got married in vegas oops"},
  {text: "accidentally crashed this wedding, but hey you’re pretty cute"},
  {text: "i was deliberately not invited to this wedding so im crashing it anyways, even if that means the angry hot maid of honor is going to murder me"},
  {text: "you’re the hot stripper at my friend’s bachelor(ette) party"},
  {text: "hey i’m the best man, you’re a bridesmaid, let’s do this thing?"},
  {text: "i know im supposed to be your best man/maid of honor, but maybe i should mention now that i’m in love with you"}, 
  {text: "i’m a wedding planner and you don’t believe in marriage"},
  {text: "i’m your wedding planner, but i’m also falling in love with you"},
  {text: "i’m the wedding planner, and you’re the best man/bridesmaid"},
  {text: "my ex just invited me to their wedding and i need you to be my date so it doesnt look like ive spent the last few years failing to get over them."},
  {text: "it’s my younger siblings wedding and my mother won’t shut up about how i’m going to die alone"},
  {text: "i need a date so i’m hiring you off craigslist, please don’t be a serial killer"},
  {text: "wow i never knew bride/groom had such a hot sibling"},
  {text: "our parents are getting married, and it’s a little weird, but you’re really hot"},
  {text: "you're the dj/wedding singer at my friends wedding and you just played my song."},
  {text: "i’m really drunk, please help me get safely out of the way so i don’t ruin my friends wedding."},
  {text: "our weirdo friends are throwing a wedding for their dogs and we both got dragged along."},
  {text: "i’m stuck at this stupid wedding, so please bartender keep the drinks coming"},
  {text: "they said ‘speak now or forever hold your peace’ so i’m speaking up"},
  {text: "i’m a runaway bride/groom and you’re driving my getaway car"},
  {text: "my bride/groom ditched me at the altar, but fuck them i’m taking this honeymoon anyway."},
  {text: "it’s our honeymoon but we’re spies/secret agents/whatever and bad guys keep appearing to ruin everything."},
  {text: "we’re planning a mutual friend’s wedding"},
  #frozen in time (-7, id 7)
  {text: "i’m a immortal who just woke up from a ‘nap’ what the fuck is this what the fuck is that "},
  #school (-8, id 8)
  {text: "our prom dates just ditched us for each other let’s show them what they’re missing out on"},
  {text: "Local teenage delinquent/Head of chastity club"},
  {text: "you were my rival in first grade and damn you’ve gotten really hot since then"},
  {text: "awkward teenage spin the bottle/seven minutes in heaven"},
  {text: "forced lab partners"},
  {text: "high school teachers "},
  #teacher/librarian (-9, id 8, id 9)
  {text: "language teachers who compete to see who can make each other more flustered in front of the class in the other language"},
  {text: "i teach your child and we have very important meetings about their education"},
  #boarding school (-10, id 8, id 10)
  {text: "preppy boarding school, one of them is there on scholarship"},
  #college/university/higher ed (-11, id 11)
  {text: "drama school rivals being cast as romantic opposites because they have “crazy sexual tension” according to their director"},
  {text: "we’re the only ones on campus who didn’t go home for christmas"},
  {text: "can u help me sneak my cat into my dorm"},
  {text: "accidentally got assigned the same library study room so I guess we’ll have to share for the semester"},
  {text: 'you just joined the -sports team here- that i’m the captain of'},
  {text: "I’m really passionate about this cause and I will give you this flier if I have to shove it down your throat"},
  {text: "vicious battle over the only left handed desk in the room"},
  {text: "my roommate’s boyfriend is staying over so can I please sleep on your floor"},
  {text: "it’s pouring and my final paper is in my backpack so I guess we’re stuck under this tiny awning together. do you think they’d deliver pizza here"},
  {text: "hey I have to photograph someone for class will you be my model"},
  {text: "hey I have to take someone’s blood pressure for class will you be my victim"},
  {text: "it’s 3 am and I’m still in the library studying for finals and I’m losing my grip on reality and I think I just saw a ghost"},
  {text: "we’re the only people who ever talk in discussions it’s awful"},
  {text: "this awesome professor only has one TA slot and we’re rivals"},
  {text: "I found your USB drive still in the computer"},
  {text: "I thought I was the only one who liked the waffle station in the cafeteria"},
  {text: "you keep reserving the good study room in the corner of the library with the windows"},
  {text: "we’re studying in the library and there are two people very obviously fucking in the stacks and we keep sharing embarrassed glances"},
  {text: "we’re both donating blood in the blood donation van in the quad to get out of the same class"},
  {text: "you decked me in the head while you were playing frisbee golf"},
  {text: "wait, I actually have a competent lab partner?"},
  {text: "you’re the RA and you’re trying to bust me for having hermit crabs"},
  {text: "you’re baking cookies in the communal kitchen at 3am and I’m angry but also really hungry"},
  {text: "what are you doing at this table at the career fair"},
  {text: "waiting for office hours"},
  {text: "I’ve been sitting in this seat all semester why did you decide to sit in it today"},
  {text: "You peed on my car. You were drunk. I was in the car. There will be hell to pay."},
  {text: "We started racing up the three flights of stairs to class for some reason and we can’t stop"},
  {text: "You’re REALLY GOOD at using the right search terms for the academic databases and I’m on a deadline"},
  {text: "my friend dragged me to this party and I just saw my ex quick make out with me"},
  {text: "we’re always at the fitness center at the same time and end up competing on the treadmill"},
  {text: "sorry my roommate puked on your shoes"},
  {text: "can I borrow a dryer sheet? I ran out and the ones in the vending machine give me a rash"},
  {text: "your school mailbox is right next to mine"},
  {text: "I saw you sneaking captain crunch and cutlery out of the dining hall"},
  {text: "My roommate borrowed your contraband hotpot and managed to set it on fire"},
  {text: "You keep using my preferred shower stall in the floor bathrooms when I’m trying to get ready for class"},
  {text: "My computer crashed and you’re the student worker at the IT center"},
  {text: "we’re both on althetic teams that aren’t as cool as the football team and they give us shit"},
  {text: "You’re part of the guerrilla theater club on campus and crashed my class for a performance"},
  {text: "What do you mean we’re under a tornado warning?"},
  {text: "on the same college tour"},
  {text: "got locked out of dorm room"},
  {text: "medical school"},
  #professor (-12, id 11, id 12)
  {text: "college professors"},
  #classics (-13, id 11, id 13)
  {text: "taking a course on a love elegist the same semester you discovered your sexuality"},
  {text: "Help I missed class can you lend me your notes on Martial' (2 hours later) 'that’s actually what that word means?!?"},
  {text: "Complaining about how high school students/incoming freshman think Catullus 16 is the epitome of dirty Latin and you both start quoting your own favorite passages and it escalates"},
  {text: "We’re both too poor to buy that textbook so now we’re fighting over the sole course reserve copy"},
  {text: "the euphemisms in old Loeb editions aka “um does ‘yard’ mean penis here”"},
  {text: "Group study of some not-safe-for-work-if-this-weren’t-classics topic"},
  {text: "You left the computer lab without logging off and I saw your Priapus fiction and I actually found it kinda hot"},
  {text: "Trapped in an archeological site/accidentally locked into Special Collections together"},
  {text: "Trying to decipher marginalia together and it turns out to be something explicit"},
  {text: "Passing notes because bored in a required history class on the language you don’t specialize in"},
  {text: "Class got cancelled but no one got the email because the college’s spam filter thinks the Greek quotation in the professor’s email signature is a virus"},
  {text: "Greek play, possibly involving toga mishaps"},
  {text: "Roleplay in Latin, bonus for sexy mistranslations"},
  {text: "Five-hour argument on etymology until suddenly that’s not what it’s about anymore"},
  #mythology (-14, id 14)
  {text: "Greek deity falls for a human"},
  #assassins (-15, id 15)
  {text: "your partner hired me to kill you but they’re an asshole so let’s make out instead"},
  #spies (-16, id 16)
  {text: "rival clandestine spies"},
  #hospital (-17, id 17)
  {text: "we both got in separate bar fights downtown and now we’re waiting in the ER comparing stories"},
  {text: "you have short term memory after your surgery - short term memory - surgery for your - no, short term memory - jesus christ stop asking"},
  {text: "that stupid thing i dared you to do sent you to the hospital"},
  #superhero (-18, id 18)
  {text: "we’re superheroes that got drunk last night oh god what’d we do"},
  #parties (-19, id 19)
  {text: "mutual friends always dragged to the same inane barbecues"},
  {text: "no-one-at-this-party-knows-how-to-buy-wine-let’s-go-on-a-wine-run-fellow-enthusiast-stranger"},
  {text: "i'm pretending to be ur bff bc u looked VERY uncomfortable with that person at the bar hitting on u"},
  {text: "we’re the only sober ones right now"},
  {text: "hiding-in-the-kitchen-stress-eating-because-the-ex-is-at-this-party"},
  {text: "accidentally swapped phones with someone at a party and don’t realize until their mom calls in the morning and you spend like three hours talking to this hilarious woman about life and when you go to her house to return her kid’s phone wow the kid is the really good kisser from the party last night"},
  #animals (-20, id 20)
  {text: "zookeepers"},
  {text: "ended up adopting like three dogs because that pet shelter employee is really hot"},
  {text: "you’re the crazy cat person next door and your cats keep on wandering into my yard"},
  {text: "vet clinic"},
  #shops (-21, id 21)
  {text: "got a crush on the hairdresser and now my hair is slowly getting really short"},
  {text: "ended up adopting like three dogs because that pet shelter employee is really hot"},
  {text: "last-of-an-item/this-is-the-PERFECT-turkey/pumpkin/terrible-thrift-store-sweater/etc"},
  #bookstore (-22, id 21, id 22)
  {text: "i accidentally feel asleep in the bookstore you work in cause i read so much"},
  {text: "we both tried to grab the last copy of that book in the shop"},
  #restaurant/coffee shop (-23, id 21, id 23)
  {text: "chef and waiter"},
  {text: "forced to share a table at the coffee shop a couple days in a row because crowded coffee shop and no room"},
  {text: "i purposely get your coffee order wrong just so you’ll talk to me again"},
  #sex industry (-24, id 21, id 24)
  {text: "accidentally called a sex line"},
  #grocery store (-25, id 21, id 25)
  {text: "we reached for the last box of chicken nuggets in the supermarket at the same time and there’s no way I’m letting you have it asshole"},
  {text: "two strangers locked inside a grocery store at three am together"},
  {text: "we’re both sick and we both grabbed for the last can of soup at the store"},
  #florist (-26, id 21, id 26)
  {text: "I rented the apartment above your flower shop and in the last two months you’ve gotten a new flower I’m allergic to so I keep buying bouquets until I can figure out which kind it is"},
  #bar (-27, id 21, id 27)
  {text: "new bartender at my favorite bar is unfairly attractive"},
  #bakery (-28, id 21, id 28)
  {text: "the-customer-wants-a-really-odd/passive-aggressive/insulting-message-on-their-cake baker"},
  #fandom (-29, id 29)
  {text: "wore the same obscure fandom shirt in public"},
  {text: "dungeons and dragons"},
  #convention (-30, id 29, id 30)
  {text: "met at a con where we accidentally cosplayed the fandom otp PLOT TWIST it’s our notp but god damn I wouldn’t mind making out with you"},
  {text: "we went to a con/party dressed as a couple on accident"},
  {text: "cosplayed as the same character "},
  {text: "got involved in a heated game of Smash Bros. at a con"},
  #slice of life (-31, id 31)
  {text: "street performers"},
  {text: "tried to get the candy bar that didn’t drop out of the vending machine and now my hand is stuck can u help me out"},
  {text: "met standing in the reallllllly long queue for the dressing rooms"},
  {text: "you accidentally shipped this weird thing to my apartment"},
  {text: "my roommate’s best friend is really obnoxious but also hot"},
  {text: "the 5 cent hug for charity you offered me on the street really brought out our amazing chemistry"},
  {text: "tree climbing contest but we both got stuck up on the top branches and now we have to wait for the fire department"},
  {text: "sat next to each other on a roller coaster"},
  {text: "met at a ren faire"},
  {text: "camping in the same area"},
  {text: "met at a card game competition"},
  #business/professions (-32, id 32)
  {text: "i should not be this attracted to the new intern"},
  {text: "one night stand before the first day of your new job and oops that was your new boss you were sleeping with"},
  {text: "parents are CEOs of rival companies"},
  {text: "lawyers"},
  #detective/cop/agent (-32, id 32, id 33)
  {text: "rescuing their partner from a recon mission gone wrong"},
  {text: "my new fbi partner/consultant is really hot"},
  {text: "detective partners"},
  {text: "police procedural"}
  #apocalypse (-33, id 34)
  {text: "being reunited after surviving the zombie apocalypse unknowing if the other was alive or dead"},
  {text: "this is the end of the world and we're all we've got"},
  #crime (-34, id 35)
  {text: "are we both robbing the same house oh fuck"},
  {text: "parents are heads of rival mob families"},
  {text: "trapped in a bank during a robbery"},
  {text: "i just committed a crime and i need to use you as a hostage i am so sorry"},
  #weather (-35, id 36)
  #snow (-36, id 37)
  {text: "we were both working during the holidays but got snowed in at the office"},
  #rain (-37, id 38)
  {text: "It’s raining and u forgot your umbrella so come over and stand under mine while we wait for the bus"},
  #paranormal (-38, id 39)
  {text: "i’m a ghost and you’re a ghost hunter"},
  {text: "this ghost led me to you"},
  #music (-39, id 40)
  {text: "I was singing in public and you decided to join in and now we’re singing a dramatic duet together also what’s your number"},
  {text: "we have to sing a duet together but i hate you"},
  {text: "you’re singing my favorite song but you’re singing it wrong"},
  #summer camp (-40, id 41)
  {text: "lifeguards at a summer camp"},
  {text: "camp counselors at the same sleep away camp"},
  #transit (-41, id 42)
  {text: "we’re strangers but i absolutely hate your music taste and i feel the need to tell you this on a crowded subway"},
  {text: "we’re the only ones in this subway car and the metro broke down"},
  {text: "accidentally fell in your lap while standing on this crowded bus"},
  {text: "ride the same bus together literally every day"},
  #travel (-42, id 43)
  {text: "you’ve been playing guitar in the hall of the hotel since three in the morning and i came down to tell you to shut the fuck up"},
  {text: "incredibly long crosscountry train ride"},
  {text: "stuck-in-an-airport-because-the-flights-were-SO-VERY-delayed-and-it’s-like-two-am"},
  {text: "hurricane during a beach trip"},
  #magic (-43, id 44)
  {text: "Hogwarts"},
  #family (-44, id 45)
  {text: "you’re my siblings’s best friend and i absolutely hate you but pretend to be my boy/girlfriend to piss off my family"},
  {text: "my new best friend’s sibling is so hot"},
  {text: "childhood friends with adjoining houses/rooms"},
  {text: "sent to live with cousins"},
  {text: "pretending to be siblings because of reasons"},
  {text: "teaming up to rescue respective abducted children"},
  {text: "pseudo-adopting-the-runaway-i-ran-into"},
  {text: "kids go to the same school"},
  {text: "little kids getting way too caught up in make-believe"},
  #winter (-45, id 46)
  #spring (-46, id 47)
  #summer (-47, id 48)
  #fall/autumn (-48, id 49)
  {text: "i got caught staring at my adult neighbour raking up a bunch of leaves in their backyard and jumping into them and now have to awkwardly pretend i saw nothing"},
  {text: "met at a pumpkin patch fighting over the same perfectly round and picturesque pumpkin"},
  {text: "i ordered a pumpkin spice latte at starbucks and you made a heart with the foam and i decided to drink it here so i can smile at you some more"},
  {text: "this stranger on the street corner looks like they're severely unprepared for this cold weather, here, take my scarf, i was planning on donating it to goodwill anyways"}
])