language: ruby

# cache: bundler

# before_install: gem install bundler

rvm:
  - 2.0.0

before_script:
  - psql -c 'create database feed-the-bunny_test;' -U postgres

script: 'bundle exec rspec spec/'

notifications:
  email: false