language: ruby

# cache: bundler

# before_install: gem install bundler

rvm:
  - 2.0.0

gemfile:
  - gemfiles/gemfile-travis

before_script:
  - psql -c 'create database feed_the_bunny_test;' -U postgres

script: 
  - 'rspec'

notifications:
  email: false