# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d7aa42a830463307640b61e98c7e72343cb1b9aa821cb27b0424c82445531f426c20cee8e5f0c0bfcff67462505c5417c5048d32fe851be506285ff13707d93

test:
  secret_key_base: 639b7e645a60b8e960fb4339701f816b8046469698bba73f3b96e0699ddf0a7caf028fa681f826ebd37469d973edb80fdf2a3b830183f18332e2e7d69e792ca6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
