Category.create!([
  {label: "mythical creatures"},
  {label: "holidays"},
    {label: "Chanukah"},
    {label: "Christmas"},
    {label: "Halloween"},
  {label: "wedding/engagement"},
  {label: "frozen in time"},
  {label: "school"},
    {label: "teacher/librarian"},
    {label: "boarding school"},
    {label: "college/university"},
  {label: "assassin(s)"},
  {label: "spies"},
  {label: "hospital"},
    {label: "amnesia"},
  {label: "superhero"},
  {label: "drinking"},
  {label: "parties"},
  {label: "animals"},
  {label: "fiction becomes reality"},
  {label: "customer"},
    {label: "bookstore"},
    {label: "restaurant/coffee shop"},
    {label: "salon"},
    {label: "animal shelter"},
    {label: "sex industry"},
    {label: "grocery store"},
    {label: "florist"},
    {label: "bar"},
    {label: "bakery"},
  {label: "fandom"},
    {label: "convention"},
  {label: "random happenings"},
  {label: "mythology"},
    {label: "Greek"},
    {label: "Latin"},
  {label: "business/professions"},
    {label: "detective/cop/agent"},
  {label: "apocalypse"},
  {label: "crime"},
  {label: "weather"},
    {label: "snow"},
    {label: "rain"},
  {label: "paranormal"},
  {label: "music"},
  {label: "summer camp"},
  {label: "vacation"},
  {label: "travel"},
  {label: "magic"},
  {label: "theme park"},
  {label: "childhood"}
])
Prompt.create!([
  {text: "mermaids"},
  {text: "I accidentally set the kitchen on fire frying things and you are an attractive firefighter."},
  {text: "What do you mean you’ve never played strip dreidel LET ME INTRODUCE YOU TO THIS PERVERSION OF THE GAME"},
  {text: "you were walking in front of me when you tripped over your own foot and knocked over the christmas tree in the park. let me help you up and we’ll try to fix the damage"},
])
PromptCategory.create!([
  {prompt_id: 1, category_id: 1},
  {prompt_id: 2, category_id: 2},
  {prompt_id: 2, category_id: 3},
  {prompt_id: 3, category_id: 2},
  {prompt_id: 3, category_id: 3},
  {prompt_id: 4, category_id: 2},
  {prompt_id: 4, category_id: 4}
])
